### ISSUE TITLE
Can we pass --unpack argument to the asar option?

### ISSUE THREAD

**Issue by hankbao** [maxogden/electron-packager#101]
I'd like to exclude some node native addons from the output asar file. But I haven't figured out how to pass the --unpack argument to asar option. Does electron-packager support --unpack argument? Please give me some hints. Thanks a lot.

**Comment by kfranqueiro** [comment]
It seems like either the `--ignore` or `--prune` option in electron-packager would allow you to do what you want.  `--ignore` allows you to specify patterns that won't be copied into the releases to begin with (and thus won't be included in app.asar either), and `--prune` will run `npm prune --production` on the copied application.

**Comment by hankbao** [comment]
The `--unpack` argument of asar prevents the specific files from been packing into the archive but still put  them in an app.asar.unpacked folder. The you can ship that folder together with the app.asar. This is important because currently electron can not require a native addon in an asar archive directly. Electron has to unpack the addon into tmp then load it from there. However this kind of behavior is in disfavor with anti-virus softwares. I believe that both `--ignore` and `--prune` don't perform like `--unpack`.

For the detail, please check: http://electron.atom.io/docs/v0.29.0/tutorial/application-packaging/

**Comment by ssreekanth** [comment]
+1

**Comment by maxogden** [comment]
released as 5.1.0

**Comment by hankbao** [comment]
:+1:  Thanks
