### ISSUE TITLE
Adding `NSHumanReadableCopyright` to plist

### ISSUE THREAD

**Issue by unindented** [maxogden/electron-packager#104]
It'd be good to be able to add `NSHumanReadableCopyright`:

```xml
	<key>NSHumanReadableCopyright</key>
	<string>Created by Daniel Perez Alvarez 
Copyright © 2015 FooBar Inc. All rights reserved.
</string>
```

It'd allow us to give some more info in the *About* dialog:

![screen shot 2015-07-17 at 17 39 09](https://cloud.githubusercontent.com/assets/69485/8752217/c45c0404-2caa-11e5-8cbc-04be36423e73.png)

And in the Quick Look preview:

![screen shot 2015-07-17 at 17 39 37](https://cloud.githubusercontent.com/assets/69485/8752230/df9748f0-2caa-11e5-957c-d76a1095e06b.png)

I'd implement this myself, but I don't know how we'd pass the info... The project uses `version-string` for Windows specific stuff, but maybe we'd benefit from generic-named attributes that can apply to multiple platforms.

What do you guys think?

**Comment by hankbao** [comment]
:+1:

**Comment by erkyrath** [comment]
See https://github.com/maxogden/electron-packager/pull/253

**Comment by malept** [comment]
Actually, see #223.
