### ISSUE TITLE
Mac: .lproj directories not created in output app

### ISSUE THREAD

**Issue by seanchas116** [maxogden/electron-packager#111]
Hi,

I found that `{language name}.lproj` directories, which are included in `Contents/Resources/` in original Electron.app, are not included in my apps packaged by electron-packager.

While `*.lproj` are empty directories, it seems that they are used to determine what languages are supported in apps.
So Electron's `navigator.language` always returns `en-US` if they are missing and it's problematic for i18n.

I found the same problem (no `*.lproj` files) when I use [extract-zip](https://github.com/maxogden/extract-zip) to extract release zip files of Electron.

## Environment

* OS X 10.10.4
* electron-packager 5.0.1

**Comment by maxogden** [comment]
upstream issue https://github.com/maxogden/extract-zip/issues/6

**Comment by maxogden** [comment]
fixed in 1.1.0 of extract-zip
