### ISSUE TITLE
Rename to `electron-packager`

### ISSUE THREAD

**Issue by sindresorhus** [maxogden/electron-packager#12]
And look for the `electron` binary instead: https://github.com/maxogden/atom-shell-packager/blob/a6cf85d0f6d81e5a497d8789a68480087873c643/index.js#L19

**Comment by zckrs** [comment]
:+1:

**Comment by cheeaun** [comment]
:+1:

**Comment by maxogden** [comment]
done in 3.0.0

**Comment by zckrs** [comment]
:clap:
