### ISSUE TITLE
Default '--version' value?

### ISSUE THREAD

**Issue by fritx** [maxogden/electron-packager#122]
```js
if (!opts.version) return cb(new Error('Must specify version'))
```

As [index.js#L153](https://github.com/maxogden/electron-packager/blob/master/index.js#L153) it seems that the --version flag is required
But it seems to bring troubles to writing build scripts
Can we auto detect from '~/.electron' directory and fetch the latest version as default?
Or any tips? Thanks. :smile:

Also, default '--platform' and '--arch'?

**Comment by iamdriz** [comment]
Yeah this would awesome! As I have just had an issue where we were building from old versions of Electron as we had the versions hard-coded in the gruntfiles. So to have it default to latest version if none is specified would be perfect.

**Comment by fritx** [comment]
Oh it's awesome that i'm just viewing  [an issue opened by you](https://github.com/atom/electron/issues/991).. quite a coincidence!

**Comment by malept** [comment]
You may be interested in PR #94.

**Comment by fritx** [comment]
@malept cool

**Comment by sleepygarden** [comment]
I've written a little build.js script which doesn't rely on npm as a module (sort of, it uses the global npm cli) and can pinpoint both the local and latest version and handle timeouts.

```js
function run_cmd(cmd, args, callBack ) {
    var spawn = require('child_process').spawn;
    var child = spawn(cmd, args);
    var resp = "";

    child.stdout.on('data', function (buffer) { resp += buffer.toString() });
    child.stdout.on('end', function() { callBack (resp) });
    return child;
}

function latestElectronVersion(versionCallback){
    var proc, timeout;
    console.log('Looking up latest Electron version...');
    var proc = run_cmd('npm',['view','electron-prebuilt','version'],function(versionString){
        versionCallback(versionString.trim());
        clearTimeout(timeout);
    });
    timeout = setTimeout(function() {
        console.error('Latest Electron version lookup timed out');
        proc.kill();
        process.exit(1);
    }, 1000 * 10); // 10s
}

function localElectronVersion(versionCallback){
    console.log('Looking up local Electron version...');
    run_cmd('npm',['list', 'electron-prebuilt', '--json'], function(json){
        versionCallback(JSON.parse(json).dependencies['electron-prebuilt'].version);
    });
}
```

**Comment by malept** [comment]
#94 has been merged, it defaults to the Electron version specified by `package.json`.

**Comment by fritx** [comment]
cool
