### ISSUE TITLE
How to Set Linux Icon

### ISSUE THREAD

**Issue by jlord** [maxogden/electron-packager#128]
Am opening a separate issue here rather than carry on in #125.

I've not been able to set an icon for the packaged Linux version of my app. It's not documented and must work differently than OS X or Windows? In the other thread it was mentioned that you just need to set `icon` in `BroswerWindow`, however, that doesn't work for me. Perhaps I'm missing something obvious? 

Either way it would be good to get it stated clearly so that we can add it to the documentation :book: 

I set `icon` in my `BrowserWindow` [here](https://github.com/jlord/git-it-electron/blob/master/main.js#L29). I've tried it both as a `NativeImage` and as the path to the `.png` via `iconPath`. I get the same results.

When using `electron-packager` I'm running [this npm script](https://github.com/jlord/git-it-electron/blob/master/main.js#L29). I've tried it with the `--icon` flag and without along with both variants of the `main.js` code I mention :point_up: 

I still do not get my icon as the app's icon in the file manager or in the dock:

![appicon](https://cloud.githubusercontent.com/assets/1305617/9726617/4caeb748-55aa-11e5-97ab-6c7f58dca929.png)

![docicon](https://cloud.githubusercontent.com/assets/1305617/9726622/5f5bbc1a-55aa-11e5-8adc-50d2ed35862f.png)

Are there other formatting specifications like size or color type? My image is [here](https://github.com/jlord/git-it-electron/blob/master/assets/git-it.png).

**Comment by malept** [comment]
It's not going to show up in the file manager, because I don't think there's a(n [XDG](http://freedesktop.org)) standard for icons in binaries.

Could you try it again after fixing the directory name typo [here](https://github.com/jlord/git-it-electron/commit/5311366b31d0a0056d99cb66103d91e52c78359a#diff-7a9076d6d94e62c13d641aa71f19ae8eR18)?

**Comment by maxogden** [comment]
Ah we should probably mention in the readme then that linux dock icons aren't supported at this time

**Comment by maxogden** [comment]
Oh I got that backwards, it won't work in the file manager but it will work in the dock.

**Comment by jlord** [comment]
> directory name typo

Gahhhh :relaxed: Ok, works in dock now :100: 

> It's not going to show up in the file manager, because I don't think there's a(n XDG) standard for icons in binaries.

Hmm. I don't know much (anything) about this as of yet, but if Atom has it then everyone should be able to have it :smile: so I'll try and dig into this week at work.

**Comment by malept** [comment]
FYI, I've tried to make the section on icons & Linux clearer (with an extra note about file extensions in general, per @kfranqueiro) in 9ed594c.

**Comment by maxogden** [comment]
@malept ahhh excellent thanks!

**Comment by gameslayer** [comment]
I am still having the same issue but on Xubuntu, I had it showing a icon at one point but now its not and I used the --icon= option and still not working.

**Comment by malept** [comment]
Per the [`icon` parameter docs](https://github.com/electron-userland/electron-packager/blob/master/docs/api.md#icon), for Linux you need to set the `icon` argument when you make a `BrowserWindow`. Make sure you set it to a `NativeImage` that points to a valid PNG.

**Comment by gameslayer** [comment]
@malept can you please give a example on how to do it on the BrowserWindow

This is a snippet of my code 
 });
  // Create the browser window.
  mainWindow = new BrowserWindow ({'width':1200,'height':900,icon: __dirname + '/icon.ico'});
  // and load the index.html of the app.
  mainWindow.loadUrl('examplewebsite.com');
  mainWindow.setMenu(null);
  // Emitted when the window is closed.
  mainWindow.on('closed', function() {
    // Remove mainWindow.on('closed', function() { if you want the menu back
    // Dereference the window object, usually you would store windows
    // in an array if your app supports multi windows, this is the time
    // when you should delete the corresponding element.
    mainWindow = null;
  });
});

**Comment by malept** [comment]
This is an example of mine that I know works, because I use Xfce (although it's CoffeeScript, not JavaScript): https://github.com/malept/gmusicprocurator-app/blob/master/src/main.coffee#L14-L21

**Comment by gameslayer** [comment]
@malept I tried adding in 

  icon = NativeImage.createFromPath("#{__dirname}/icon-48.png")
  options =
    icon: icon
    width: 1280
    height: 720

so my code looks like this 
app.on('ready', function() {
  icon = NativeImage.createFromPath("#{__dirname}/node_modules/icon.png")
  options =
    icon: icon
    width: 1280
    height: 720
  app.on('browser-window-created',function(e,window) {
        window.setMenu(null);
    });
  // Create the browser window.
  mainWindow = new BrowserWindow ({'width':1200,'height':900,icon: __dirname + '/icon.ico'});
  // and load the index.html of the app.
  mainWindow.loadUrl('http://examplewebsite.com');
  mainWindow.setMenu(null);
  // Emitted when the window is closed.
  mainWindow.on('closed', function() {
    // Remove mainWindow.on('closed', function() { if you want the menu back
    // Dereference the window object, usually you would store windows
    // in an array if your app supports multi windows, this is the time
    // when you should delete the corresponding element.
    mainWindow = null;
  });
});


what do I do or do wrong?

**Comment by malept** [comment]
I did say it was in CoffeeScript, which has a different syntax from JavaScript and will not execute in Node unless it's transpiled into JavaScript.

In your code, you want to do the following:

```javascript
NativeImage = require('native-image');

// [...more of your code before the snippet you pasted...]

// Create the browser window.
mainWindow = new BrowserWindow ({'width': 1200, 'height': 900, icon: NativeImage.createFromPath(__dirname + '/icon.ico')});

// [...the rest of the snippet of code you pasted...]

**Comment by gameslayer** [comment]
Ah right I see and I also see now I need another dependency  "NativeImage" how do I get this?

**Comment by malept** [comment]
It is bundled with Electron.

**Comment by gameslayer** [comment]
I added it and NativeImage = require('native-image'); above it but the icon still hasn't come up, I even changed '/icon.ico')}); to '/node_modules/icon.ico')});

This is my code 
app.on('ready', function() {
  app.on('browser-window-created',function(e,window) {
        window.setMenu(null);
    });
  // Create the browser window.
  NativeImage = require('native-image');
  mainWindow = new BrowserWindow ({'width':1200,'height':900, icon: NativeImage.createFromPath(__dirname + '/node_modules/icon.ico')});
  // and load the index.html of the app.
  mainWindow.loadUrl('https://examplewebsite.com');
  mainWindow.setMenu(null);
  // Emitted when the window is closed.
  mainWindow.on('closed', function() {
    // Remove mainWindow.on('closed', function() { if you want the menu back
    // Dereference the window object, usually you would store windows
    // in an array if your app supports multi windows, this is the time
    // when you should delete the corresponding element.
    mainWindow = null;
  });
});

**Comment by malept** [comment]
I missed it before,  you need to set a PNG, not an ICO.

**Comment by gameslayer** [comment]
ok ill try that

**Comment by gameslayer** [comment]
Awesome that worked thanks so much!

**Comment by Autre31415** [comment]
I've done some testing on this and found out icons can work under certain conditions which I detail at:
https://github.com/electron/electron/issues/6205

**Comment by vilas2488** [comment]
Here is the solution for linux icon
 "linux": {
      "target": [
        "deb"
      ],
      "icon": ".//logoassets/uxp"
    }

in package.json put target deb for linux and give icon folder not exact icon path and name of icon is 256x256.png or any size name .then it works 
thank you!

**Comment by imkzh** [comment]
You can place your icon somewhere inside `/usr/shared/icons/hicolor/*/apps` matching the name of your package name (the one you specified in `package.json`)

> If you are not going to install the program, you can place it under `~/.local/share/icons/hicolor/*/apps`

The app icon will automatically picked by your desktop environment, and this also helps icon-theme-packages overriding your app icon to provide a consistent customizable UI.

> You can check this by quickly rename your package as `folder` (and you can see your app shown as folder when started).


> If above method not working properly with your icon, try refresh the icon cache:
> on Ubuntu, it is `sudo update-icon-caches /usr/share/icons/*`
