### ISSUE TITLE
version-string.FileVersion is not working on Windows

### ISSUE THREAD

**Issue by petrfelzmann** [maxogden/electron-packager#129]
When I use this command

`electron-packager c:\myapp MyApp --platform=win32 --arch=x64 --version=0.32.1 --app-version=1.0.0.123 --version-string.ProductVersion=1.0.0.123 --version-string.FileVersion=1.0.0.123`

then the *File version* of MyApp.exe contains 0.32.1 instead of 1.0.0.123, see the attached screenshot.

*Windows 7 x64
electron-packager v5.1.0*

![electron-packager-fileversion](https://cloud.githubusercontent.com/assets/12231141/9786139/e0f6161c-57b7-11e5-9e05-e5f2906674ea.png)

**Comment by spinico** [comment]
rcedit.exe command line has the --set-file-version "<version string>" that should be used for this (instead of --set-verson-string "FileVersion" "<version string>" as the other property are defined).

**Comment by malept** [comment]
@spinico could you create a pull request with this change?
