### ISSUE TITLE
404 Error

### ISSUE THREAD

**Issue by Opligitory** [maxogden/electron-packager#137]
when trying to package a test application with 
`"electron-packager . Test --ignore=node_modules/electron-* --version=1.0.0 --platform=all --arch=all"` 
it gave me an error 
`"Downloading electron-v1.0.0-linux-ia32.zip
Error: GET https://github.com/atom/electron/releases/download/v1.0.0/electron-v1.0.0-linux-ia32.zip returned 404
[ [Error: GET https://github.com/atom/electron/releases/download/v1.0.0/electron-v1.0.0-linux-ia32.zip returned 404] ] undefined"`

**Comment by malept** [comment]
`--version` refers to the Electron version, not the application version.
