### ISSUE TITLE
Socket hang up while building win32 x64 distribution on OSX machine

### ISSUE THREAD

**Issue by Rustem** [maxogden/electron-packager#138]
electron version = 0.29.2
Full command:
`electron-packager . sberko --out=distr/sber --platform=win32 --arch=x64  --version=0.29.2 --icon=assets/icon.ico --overwrite --ignore=\"(distr|node_modules/electron-packager|node_modules/electron-prebuilt|debug.log)\"`

**Comment by malept** [comment]
Could you explain what "socket hang up" means?

**Comment by Rustem** [comment]
@malept Yes, of course. As I understood electron-download tries to download the specified version of electron if it is not present. In my case it tries to download electron-v0.29.2-win32-x64.zip release.

**Comment by malept** [comment]
@Rustem is there any terminal output?

**Comment by Rustem** [comment]
For example below is the log while I am trying to build under electron 0.33

`electron-packager . sberko --out=distr/sber --platform=win32 --arch=x64  --version=0.33.0 --icon=assets/icon.ico --ov│  Config file is optional. Other configuration arguments have higher
erwrite --ignore="(distr|node_modules/electron-packager|node_modules/electron-prebuilt|node_modules/electron-builder|no│  priority if given, and will override those specified in the config file
de_modules/electron-download|debug.log)"                                                                               │
                                                                                                                       │  -c CONFIG, --config CONFIG
Downloading electron-v0.33.0-win32-x64.zip                                                                             │                        Path to config file. If this is not set then you must
Error: socket hang up                                                                                                  │                        set at least --phone and --cc arguments
[ { [Error: socket hang up] code: 'ECONNRESET' } ] undefined                                                           │  -m MCC, --mcc MCC     Mobile Country Code. Check your mcc here:
                                                                                                                       │                        https://en.wikipedia.org/wiki/Mobile_country_code
npm ERR! Darwin 14.3.0                                                                                                 │  -n MNC, --mnc MNC     Mobile Network Code. Check your mnc from
npm ERR! argv "node" "/usr/local/bin/npm" "run" "build:sber"                                                           │                        https://en.wikipedia.org/wiki/Mobile_country_code
npm ERR! node v0.12.6                                                                                                  │  -p PHONE, --phone PHONE
npm ERR! npm  v3.3.3                                                                                                   │                        Your full phone number including the country code you
npm ERR! code ELIFECYCLE                                                                                               │                        defined in 'cc', without preceeding '+' or '00'
npm ERR! ko@1.0.0 build:sber: `electron-packager . sberko --out=distr/sber --platform=win32 --arch=x64  --version=0.33.│  -C CC, --cc CC        Country code. See http://www.ipipi.com/help/telephone-
0 --icon=assets/icon.ico --overwrite --ignore="(distr|node_modules/electron-packager|node_modules/electron-prebuilt|nod│                        country-codes.htm. This is now required
e_modules/electron-builder|node_modules/electron-download|debug.log)"`                                                 │
npm ERR! Exit status 1                                                                                                 │Modes:
npm ERR!                                                                                                               │  -r (sms|voice), --requestcode (sms|voice)
npm ERR! Failed at the ko@1.0.0 build:sber script 'electron-packager . sberko --out=distr/sber --platform=win32 --arch=│                        Request the digit registration code from Whatsapp.
x64  --version=0.33.0 --icon=assets/icon.ico --overwrite --ignore="(distr|node_modules/electron-packager|node_modules/e│  -R code, --register code
lectron-prebuilt|node_modules/electron-builder|node_modules/electron-download|debug.log)"'.                            │                        Register account on Whatsapp using the code you
npm ERR! This is most likely a problem with the ko package,                                                            │                        previously received
npm ERR! not with npm itself.                                                                                          │(wazzup)MacBook-Pro-Rustem% python
npm ERR! Tell the author that this fails on your system:                                                               │Python 2.7.6 (default, Sep  9 2014, 15:04:36) 
npm ERR!     electron-packager . sberko --out=distr/sber --platform=win32 --arch=x64  --version=0.33.0 --icon=assets/ic│[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.39)] on darwin
on.ico --overwrite --ignore="(distr|node_modules/electron-packager|node_modules/electron-prebuilt|node_modules/electron│Type "help", "copyright", "credits" or "license" for more information.
-builder|node_modules/electron-download|debug.log)"                                                                    │>>> a = [1,2,3]
npm ERR! You can get their info via:                                                                                   │>>> next(a)
npm ERR!     npm owner ls ko                                                                                           │Traceback (most recent call last):
npm ERR! There is likely additional logging output above.                                                              │  File "<stdin>", line 1, in <module>
                                                                                                                       │TypeError: list object is not an iterator
npm ERR! Please include the following file with any support request:                                                   │>>> a
npm ERR!     /Users/rustem/projects/sber/sberbank.services.kodeskt/npm-debug.log `

**Comment by malept** [comment]
This looks more like a problem with your internet connection, not with electron-packager.

**Comment by jingweno** [comment]
It didn't hang for me. But I'm getting:

```
Packaging app for platform win32 x64 using electron v0.31.2
spawn wine ENOENT
```

**Comment by malept** [comment]
@jingweno this is a different problem, you do not have Wine installed. Please see [the README](https://github.com/maxogden/electron-packager/blob/master/readme.md#building-windows-apps-from-non-windows-platforms) for creating windows builds with a custom app icon.

**Comment by Rustem** [comment]
Thank you. I think that's closed issue.

**Comment by jingweno** [comment]
@malept Cool thanks. Installing `wine` makes it work!!
