### ISSUE TITLE
my linux build takes up to 13GB

### ISSUE THREAD

**Issue by hardywu** [maxogden/electron-packager#139]
Mac and windows build work just fine. But the linux build is eating up my ssd.
```
electron-packager ./ Flarx --out=dist --platform=linux --arch=ia32 --version=0.33.0 --icon=assets/linux/icon.ico
```
All the mess comes from the resulting `resources` directory in the output, which contains a copy of my entire project.

**Comment by malept** [comment]
Have you tried adding `--ignore=dist` ?

**Comment by hardywu** [comment]
Oops. Thanks for pointing out.
