### ISSUE TITLE
404 when generating app

### ISSUE THREAD

**Issue by danielmeneses** [maxogden/electron-packager#140]
Hi there,

i receive a 404 when trying to generate an electron app for win32:
My code:
<pre>
electron-packager ./ video-call --platform=win32 --arch=x64 --version=0.0.1
</pre>

Error:
<pre>
Downloading electron-v0.0.1-win32-x64.zip
Error: GET https://github.com/atom/electron/releases/download/v0.0.1/electron-v0.0.1-win32-x64.zip returned 404
[ [Error: GET https://github.com/atom/electron/releases/download/v0.0.1/electron-v0.0.1-win32-x64.zip returned 404] ] undefined
</pre>

thanks,
Daniel

**Comment by kfranqueiro** [comment]
This sounds like the same thing as #137.  The value of `--version` is the *electron* version you want to use, not your app's version.

**Comment by amitpatil321** [comment]
Renaming --version to --electron-version atleast removed that 404 error. Now the package is downloading. Will update here is this solution fixed it completely or not

**Comment by malept** [comment]
`--electron-version` was never implemented. `--version` is now an optional parameter, it will be inferred from the version of `electron-prebuilt` that you have installed if you do not specify it.

**Comment by malept** [comment]
Also, the `--app-version` parameter was added in the same release ([5.2.1](https://github.com/electron-userland/electron-packager/blob/master/NEWS.md#521---2016-01-17)).
