### ISSUE TITLE
Related project

### ISSUE THREAD

**Issue by vrunoa** [maxogden/electron-packager#147]
Hey @maxogden, a few time ago I created [electron-packager-interactive](https://github.com/Urucas/electron-packager-interactive), an interactive cli to create electron-packages based on electron-packager. 
I was wondering if you find this project interesting enough to add it to the REAMDE.md under related projects for other users to know about it. 

P.S.: Thanks for **electron-packager**

**Comment by maxogden** [comment]
hey thats pretty cool, feel free to send a PR adding it to the readme at the bottom :D

**Comment by vrunoa** [comment]
Cool @maxogden, just created a [PR](https://github.com/maxogden/electron-packager/pull/148).
