### ISSUE TITLE
Download Darwin Issue

### ISSUE THREAD

**Issue by tonyspiro** [maxogden/electron-packager#153]
Tried to run the command:
electron-packager ./electron FooBar --platform=darwin --arch=x64 --version=0.1

And got:
Downloading electron-v0.1-darwin-x64.zip
Error: GET https://github.com/atom/electron/releases/download/v0.1/electron-v0.1-darwin-x64.zip returned 404
[ [Error: GET https://github.com/atom/electron/releases/download/v0.1/electron-v0.1-darwin-x64.zip returned 404] ] undefined

I'm on OSX Yosemite 10.10.2

Thanks.

**Comment by malept** [comment]
`--version` refers to the Electron version, not the application version.
