### ISSUE TITLE
App icon for Windows

### ISSUE THREAD

**Issue by ValentinCreative** [maxogden/electron-packager#160]
Hi, 

I can't find a way to add an icon to the windows exe build. 
As I can't add icon with the --icon argument (see #159), I can't find another way to do it. 

Also, is there a way to add a tile image ?

**Comment by jinpark** [comment]
It says in the readme

> Building windows apps from non-windows platforms

> If you run this on windows and you want to set the icon for your app using the --icon option, it requires running a thing called rcedit.exe (via this), which means you will need to install wine and have it available in your path. To do this on Mac OS you can brew install wine.

**Comment by malept** [comment]
What do you mean by "tile image"?

**Comment by ValentinCreative** [comment]
@jinpark Ok thanks, i'll check that out

@malept this images in the start menu 
![Tile image](http://4dm7pi3anfms2bn7sk7u16h1.wpengine.netdna-cdn.com/wp-content/uploads/2014/10/windows_10_features_start_menu.jpg)

**Comment by malept** [comment]
If tile images are supported, it would most likely be in the [Electron documentation](http://electron.atom.io/docs/v0.33.0/).
