### ISSUE TITLE
Add support for distribution.dist files for OSX packages.

### ISSUE THREAD

**Issue by thomasdarimont** [maxogden/electron-packager#162]
When packaging applications for OSX, one can customize  things like e.g. the background image of the "installer" via a [distribution.dist](https://developer.apple.com/library/mac/documentation/DeveloperTools/Reference/DistributionDefinitionRef/Chapters/Introduction.html#//apple_ref/doc/uid/TP40005370-CH1-DontLinkElementID_16) file.

It would be great if this could be supported in electron-packager.
Some additiotional info can be found [here](http://stackoverflow.com/questions/11487596/making-os-x-installer-packages-like-a-pro-xcode-developer-id-ready-pkg).

**Comment by maxogden** [comment]
@thomasdarimont if I'm understanding your use case correctly I think this would live in a module that creates installers, e.g. https://www.npmjs.com/package/electron-builder

**Comment by thomasdarimont** [comment]
Thanks for the hint, I'm still pretty new to the electron toolchain - it seems that electron-builder is what I need :) I think this issue can be closed then.
