### ISSUE TITLE
Add ability to package OSX build as an App Store compliant app

### ISSUE THREAD

**Issue by herrmannplatz** [maxogden/electron-packager#163]
Since the electron team made a big step forward and provided an mac appstore compliant version of electron, it would be really nice to use electron packager to bundle these apps.

I uploaded an app a couple of days before and based on what apple complained, the following things need to be changed.
1. Adjust Info.plist (LSApplicationCategoryType, NSHumanReadableCopyright)
2. Set proper bundle name, identifier and executable for all Electron Helpers
3. Sign the app and create a package

I hacked a [version](https://github.com/herrmannplatz/electron-packager/tree/feature/app-store-compliant) that includes step 1 and 2. I could make a proper PR with test if wanted. The last step ist most likely the hardest issue, since it includes also adding all of the entitlements. You can find a script to sign the app with entitlements in the [electron docs](https://github.com/atom/electron/blob/master/docs/tutorial/mac-app-store-submission-guide.md). ~~What is not mentioned in the docs is that you need to define the [capabilities of your sandboxed app](https://developer.apple.com/library/mac/documentation/Miscellaneous/Reference/EntitlementKeyReference/Chapters/EnablingAppSandbox.html#//apple_ref/doc/uid/TP40011195-CH4-SW1).~~ (Note to myself... RTFM)

**Comment by maxogden** [comment]
Is there any way we can do all that stuff with another module? i'd like to keep this one as simple as possible

**Comment by lipis** [comment]
:100:

**Comment by kfranqueiro** [comment]
I'm a little confused at where electron-packager does or should draw the line, since doesn't it already modify some plist entries?

**Comment by maxogden** [comment]
@kfranqueiro yea the first two items wouldn't be that much of a code change probably (though it would be nice some day to move *all* the plist stuff out of here). I was mostly talking about the entitlements/capabilities stuff which would be a lot of new code

**Comment by herrmannplatz** [comment]
Having the full control over what to put into the plist would solve step 1 anyway. And as electron-packager already changes the Electron Helper, it would be just straightforward to do it also for the rest.

I agree that especially the signing could be done in a different place. This is what i am doing right now.

**Comment by elronalds** [comment]
Is this issue going to involve adding the mas build to the --platform flag?  So the options would be linux, win32, darwin, mas.  Since Electron v0.34.0 introduced the new separate Mac App Store binary.

**Comment by ex3ndr** [comment]
+1

**Comment by hankbao** [comment]
+1 for a new --platform flag. Currently we have to pack our MAS build manually.

**Comment by jfurneaux** [comment]
+1

**Comment by mawie81** [comment]
I added a new mas platform on https://github.com/mawie81/electron-packager/commit/c0af8213c4c9dbba7b1808bd9083d7276b78bc3b Tests are looking good as well (the ones that require wine failed for me because I dont have it installed currently).

Tried to handle all the plist stuff in a not so repetitive manner. Could create a PR if wanted.
After manual signing and packaging the Application Loader app gave no errors and and I could upload my test app.

Maybe step 3 could be solved by adding two new entitlements parameters to pass in the child.plist and parent.plist?

**Comment by marbemac** [comment]
Huge +1 - @mawie81 was your app accepted in the end?

**Comment by malept** [comment]
FYI, PR #223 has some additional discussion and a [call for help](https://github.com/maxogden/electron-packager/pull/223#issuecomment-166159764) directed at those interested in seeing this feature integrated into electron-packager (which I assume is most of those who are subscribed to this issue).
