### ISSUE TITLE
Mac doc icon gets tiny when setProgressBar is called

### ISSUE THREAD

**Issue by MoonScript** [maxogden/electron-packager#167]
When using `electron-packager` with the `--icon` option with an `*.icns` file, my custom icon in the dock looks great:

![initial dock icon](https://cloud.githubusercontent.com/assets/1203504/10695809/5424fe6c-796b-11e5-91d6-00c9eb0289ab.png)

...but as soon as I call the [setProgressBar](http://electron.atom.io/docs/v0.34.0/api/browser-window/#win-setprogressbar-progress) method of the Electron window, the dock icon gets tiny:

![after setprogressbar is called](https://cloud.githubusercontent.com/assets/1203504/10695852/83c699e6-796b-11e5-9398-59fb058499cb.png)

I assume this is a problem with how the `electron-packager` sets up the icon, because when I do the same thing with the base Electron code (without using `electron-packager`), the default Electron dock icon stays full-size:

![electron icon unchanged](https://cloud.githubusercontent.com/assets/1203504/10695913/e6c551ae-796b-11e5-801a-cb060b063375.png)

**Comment by malept** [comment]
Have you also set [the icon option in the BrowserWindow contructor](http://electron.atom.io/docs/v0.30.0/api/browser-window/#new-browserwindow-options)?

**Comment by MoonScript** [comment]
@malept no, but I'll give that a try right now!

**Comment by MoonScript** [comment]
@malept I just added the `icon` option (using my same `*.icons` file) in my [BrowserWindow](http://electron.atom.io/docs/v0.30.0/api/browser-window/#new-browserwindow-options) call, and it had the same behavior as soon as I called [setProgressBar](http://electron.atom.io/docs/v0.34.0/api/browser-window/#win-setprogressbar-progress) the first time.  I'm using an `*.icns` file with the following icon sizes embedded in it: 32x32, 64x64, 256x256, 512x512 and 1024x1024.

**Comment by malept** [comment]
According to [the docs](http://electron.atom.io/docs/v0.30.0/api/native-image/#supported-formats), it only supports JPEG/PNG formats for that option. Try setting it to a 512x512 PNG and see what happens.

**Comment by MoonScript** [comment]
@malept I received that `*.icns` file from one of our designers and I think it was not created properly (for Mac to understand).  I just followed [this tutorial](http://applehelpwriter.com/2012/12/16/make-your-own-icns-icons-for-free/) and recreated my `*.icns` file, and now the icon stays the proper size in the dock!

![dock icon proper size with progress bar](https://cloud.githubusercontent.com/assets/1203504/10697593/569d43c8-7972-11e5-8ee3-9d86876ad0cb.png)

Sorry for taking up your time on this, and thanks for talking through it with me.
