### ISSUE TITLE
Unable to start packaged exe with asar on Windows

### ISSUE THREAD

**Issue by marsinvasion** [maxogden/electron-packager#168]
I get this error
Error: Cannot find module 'C:\Users\u\vm\win32-x64\resources\atom.asar\browser\lib\init.js'

The mac packaged and stand alone app works fine

Electron: v0.34
Windows 7

This path doesn't exist in the asar file.

**Comment by malept** [comment]
What version of electron-packager are you using?

**Comment by marsinvasion** [comment]
electron-packager@5.1.0

**Comment by marsinvasion** [comment]
If I replace app.asar with the app folder it works fine. I'm ok with that workaround. Thanks

**Comment by marsinvasion** [comment]
Rebuilt today and it works fine with asar file
