### ISSUE TITLE
Mac os X package not working

### ISSUE THREAD

**Issue by jaumard** [maxogden/electron-packager#169]
I'm trying to package with the following command : 
`electron-packager ./ MyApp --plateform=all --arch=all --version=0.34.0 --out=.`

But it's not working it show me the help and usage :
`Usage: electron-packager <sourcedir> <appname> --platform=<platform> --arch=<arch> --version=<version>...`

Any idea ? electron-packager is install globally. I'm under Mac OS X node v4.1.2

**Comment by malept** [comment]
In the command, it appears you misspelled `platform`.

**Comment by jaumard** [comment]
That's an easy one lol ^^ need some sleep sorry about this :) thanks a lot
