### ISSUE TITLE
Add option to match directories for asar unpack

### ISSUE THREAD

**Issue by sleman** [maxogden/electron-packager#171]
I need an entire folder to not be packed into the archive. Right now, the regex is matched only on the filenames. I tried doing a REGEX for file1|file2 but that did not work. It would be great to be able to ignore an entire directory from packing. Perhaps `--asar-unpack-dir` ?

**Comment by malept** [comment]
From what I can tell, we pass the `unpack` option directly to the [`asar`](https://github.com/atom/asar) library. I believe you need to file an issue upstream first to get this functionality, then we can see what we need to do in order to support it.
