### ISSUE TITLE
Windows (10): 'Product version'' remains empty

### ISSUE THREAD

**Issue by p-bakker** [maxogden/electron-packager#172]
See #166: that case started with three bullet items, but has since then focused on only the second bullet item (App name not set correctly in Windows EXE metadata).

This case is for the first bullet item: 
- If I look at the file details of the created .exe: -- the 'File version' is still set to the used Electron version, although i specify another version -- the 'Product version' is empty

While there is a related case with a PL for the 'File version' (#129/#143), I tried applying the fixes from #143 manually, but that didn't solve the problem for me.

And since also the 'Product version' is not applied, I suspect something else going on, but no clue what

**Comment by malept** [comment]
I took a quick look at the problem - it appears to be the same problem as #129, but with a different key. If I have some time today, I'll write a failing test for this.

**Comment by p-bakker** [comment]
I'm not so sure about that: while rcedit docs suggest you need to use --set-product-version "10.7", if you use --set-version-string "ProductVersion" "10.7" this also works, which is what electron-packager does.

I've tried the '--set-version-string "ProductVersion" "10.7"' option with the rcedit that electron-packager downloads and it set the 'Product version" attribute of the generated .exe just fine.

Also note that I did make the same code changes as #129 did locally and that didn't result in the FileVersion being set, so imho something else is going on... Just don't know what

**Comment by malept** [comment]
I was specifically looking at [this line of the node-rcedit README](https://github.com/atom/node-rcedit/blame/5b63a00a6d3186b4a475562c0e5f0bc885252fe9/README.md#L27).

**Comment by p-bakker** [comment]
I know that is what the docs say, but just give it a try with --set-version-string "ProductVersion" "10.7"

For me that works just as well, which means that modifying the code to use --set-product-version "10.7" instead probably won;t solve my issue

**Comment by malept** [comment]
That's what I meant by "write a failing test". I don't have a Windows environment handy at the moment, so writing a test similar to the one in #143 and seeing what happens is the easiest way for me to attempt to solve the problem.

**Comment by p-bakker** [comment]
k

Not trying to add more confusion, but for testing #1954 I setup a VM with the latest Insider built of Win10. While there the issue of duplicate icons is gone (which #1954 is about), I saw that none of the file attributes were set. And if I ran the generated .exe, it lanched, but I wasn;t able to pin it at all: right-clicking the icon in the TaksBar showed a popup menu, but the menuitem to pin the app was completely missing...

**Comment by p-bakker** [comment]
I've tested some more regarding my previous comment that a lot more stuff doesn't work with the latest insider build.

What I found is that rcedit threw an exception, because some Windows dll's were not available and thus the attributes/icon/.exe name weren't updated.

I've fixed the dll issues and after that all the stuff rcedit takes care of worked again.

But right-clicking the app in the TaskBar after launching the .exe only shows the option 'Close Window', not the App itself, nor the option to pin it.

So to me there are now 2 new issues to create:
1: exceptions thrown by rcedit don't result in logging/failing in electron-packager
2: In upcoming Windows 10 version (or at least the current build for it) the .exe is not pinnable anymore

Agree these two cases belong under electron-packager? Regarding the second: I tested with plain electron for https://github.com/atom/electron/issues/1954#issuecomment-150959890 and that I was able to pin crrectly

**Comment by malept** [comment]
1. This feels like it's an upstream problem - see: atom/node-rcedit#7
2. I would wait until there's a public release of that Windows 10 version - there may be changes between now and the release date which would fix this.

From #173:

> rcedit doesn't seem to support setting the ProductVersion to value 1. If I try setting it to 0.9 or 1.1 or any other value, the ProductVersion is properly set, if I use 1 (or 1.0) the ProductVersion is not set.
>
> So, conclusion: the fixes for FileVersion/ProductVersion work, but there is another issue in rcedit

This should be an issue filed in atom/node-rcedit.
