### ISSUE TITLE
optional arguments in readme need descriptions

### ISSUE THREAD

**Issue by maxogden** [maxogden/electron-packager#175]
I think the `asar`, `asar-unpack` and this new `asar-unpack-dir` (https://github.com/maxogden/electron-packager/pull/174) need some documentation in the README. Nowhere does it currently explain what asar is, or what the various asar options do.

Also if anyone is feeling super helpful, all of the optional arguments (under 'Optional') could use descriptions. `all` has a description, but none of the others do:

<img width="497" alt="screen shot 2015-10-27 at 9 46 28 am" src="https://cloud.githubusercontent.com/assets/39759/10765377/a9b9773c-7c8f-11e5-873e-e2579c160fd7.png">

**Comment by malept** [comment]
In terms of describing asar, something concise and then a link to the [Electron docs](http://electron.atom.io/docs/v0.34.0/tutorial/application-packaging/) should be sufficient.

**Comment by varemenos** [comment]
Also:

* ignore - RegExp
* out - String
* overwrite - Boolean
* prune - Boolean
* sign - String
* version-string - Object
