### ISSUE TITLE
App version not displaying in OSX

### ISSUE THREAD

**Issue by rmcshane** [maxogden/electron-packager#176]
I'm invoking electron-packager as such:
```bash
electron-packager ./pkg-tmp "My App Name" --platform=darwin --arch=x64 --version=0.33.6 --out="./output" --icon=./assets/icon.icns \
    --app-version="0.0.1" --app-bundle-id=com.my.org --prune --overwrite --asar
```

The build looks good except the app version doesn't show up when getting info on the .app file.  Looking at the Info.plist file inside the package contents shows that CFBundleShortVersionString is missing
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>BuildMachineOSBuild</key>
    <string>14D136</string>
    <key>CFBundleDisplayName</key>
    <string>My App Name</string>
    <key>CFBundleExecutable</key>
    <string>Electron</string>
    <key>CFBundleIconFile</key>
    <string>atom.icns</string>
    <key>CFBundleIdentifier</key>
    <string>com.my.org</string>
    <key>CFBundleInfoDictionaryVersion</key>
    <string>6.0</string>
    <key>CFBundleName</key>
    <string>My App Name</string>
    <key>CFBundlePackageType</key>
    <string>APPL</string>
    <key>CFBundleVersion</key>
    <string>0.0.1</string>
    <key>DTSDKBuild</key>
    <string>14D125</string>
    <key>DTSDKName</key>
    <string>macosx10.10</string>
    <key>DTXcode</key>
    <string>0632</string>
    <key>DTXcodeBuild</key>
    <string>6D2105</string>
    <key>LSMinimumSystemVersion</key>
    <string>10.8.0</string>
    <key>NSHighResolutionCapable</key>
    <true/>
    <key>NSMainNibFile</key>
    <string>MainMenu</string>
    <key>NSPrincipalClass</key>
    <string>AtomApplication</string>
    <key>NSSupportsAutomaticGraphicsSwitching</key>
    <true/>
    <key>CFBundleURLTypes</key>
    <array/>
  </dict>
</plist>
```

I'm using version 5.1.0 of electron-packager.  Is there another field I should be setting?  Looks to me in mac.js that app-version is all that's needed.

**Comment by malept** [comment]
Odd. I wonder why [the test](https://github.com/maxogden/electron-packager/blob/4e0746facb7337a5edfb3b1c7a63d6f5b83f599e/test/mac.js#L73) passes.

**Comment by herrmannplatz** [comment]
That is strange since [app-version](https://github.com/maxogden/electron-packager/blob/master/mac.js#L55) should set the `CFBundleVersionShortString`. But in your case it sets the `CFBundleVersion`. Using electron-packager on a daily basis and it works fine. But i am not using it via command line.

**Comment by herrmannplatz** [comment]
Tried to reproduce it, but works fine in my case

```
electron-packager@5.1.0
...
electron-packager ./ VersionTest --platform=darwin --arch=x64 --version=0.33.9 --app-version=0.0.4
```

<img width="267" alt="bildschirmfoto 2015-10-28 um 22 11 07" src="https://cloud.githubusercontent.com/assets/174685/10803105/de346260-7dc0-11e5-8502-6f030f4c0f9e.png">

**Comment by rmcshane** [comment]
I figured out my problem.  electron-packager command had been set to use a previous version.  I removed older versions, set it to 5.1.0 and now everything is fine again.

I apologize for the waste of time here, and thank you for the responses!
