### ISSUE TITLE
Process name for Windows build still says "Electron"

### ISSUE THREAD

**Issue by kethinov** [maxogden/electron-packager#179]
In task manager the process is still named "Electron" rather than showing the name of my app.

App source code: https://github.com/kethinov/DianeRehmDownloader

Command used: `electron-packager ./ "Diane Rehm Downloader" --app-bundle-id=dianerehmdownloader --icon=images/appicon.ico --out=build --overwrite=true --platform=win32 --arch=x64 --version=0.33.3 --app-version=1.0.1`

![screen shot 2015-10-31 at 7 12 02 pm](https://cloud.githubusercontent.com/assets/419567/10866418/34c32ca2-8004-11e5-9c54-9fcc7fd76f54.png)

Also, the default electron icon is still shown in the file system due to Windows build environment issues tracked in a [separate issue](https://github.com/maxogden/electron-packager/issues/53#issuecomment-152779979).

**Comment by malept** [comment]
Have you tried setting one or more of the `--version-string` options?

**Comment by kethinov** [comment]
Looks like `--version-string.FileDescription` is the one that does it. Thanks.
