### ISSUE TITLE
5.1.1 not compatible with 5.1.0

### ISSUE THREAD

**Issue by MrSurly** [maxogden/electron-packager#181]
When using version `^5.1.0` in `package.json` for electron-packager, which should mean "compatible with 5.1.0," builds are now failing.  Setting version to `=5.1.0` fixes this issue.

After some investigation, it appears that this command-line option is causing failure:
`--version-string.FileVersion agl.exe`

Ultimately, it looks like the `node-rcedit` doesn't like this.

Of course, the string 'agl.exe' probably isn't arguably a valid version, but this is a case of "works with 5.1.0, but not 5.1.1," so it could be said that 5.1.1 isn't compatible with 5.1.0.

**Comment by malept** [comment]
I would argue that `version-string.FileVersion` didn't actually work prior to 5.1.1 (see #129), so the meaning of "backwards compatible" is unclear.

**Comment by MrSurly** [comment]
You mean ... it didn't work at all?  Hmm.  That could be.  We certainly weren't relying on it being any particular value, nor did we check to see if it was set correctly.  The present "fix" is to simply not specify that option.
