### ISSUE TITLE
No app icon

### ISSUE THREAD

**Issue by oleander** [maxogden/electron-packager#19]
I'm using this to assemble my application `electron-packager build MyApp --out=dist/ --app-version=0.25.1 --icon=assets/icon.ico --prune` but the application doesn't show up with an icon.

I can see the icon when using `alert()`, but not in the dock or in finder.

I'm using the latest version (0.3.3) (but the problem remains in 0.3.1).

Here's the alert and about box.

![skarmavbild 2015-05-06 kl 19 09 28](https://cloud.githubusercontent.com/assets/220827/7498741/93e3deec-f423-11e4-8650-aaab7c8c1a29.png)

![prints](https://cloud.githubusercontent.com/assets/220827/7498790/a7d4d956-f423-11e4-8a8b-fad03f3aaf31.png)

Here's finder

![skarmavbild 2015-05-06 kl 19 10 08](https://cloud.githubusercontent.com/assets/220827/7498795/b1981e6c-f423-11e4-9a91-e4c859ff4938.png)

and the dock

![skarmavbild 2015-05-06 kl 19 09 51](https://cloud.githubusercontent.com/assets/220827/7498798/b607a24c-f423-11e4-9138-af42f3d80efd.png)

I'm using Electron 0.25.1 with node v0.12.1.

Here's the icon I'm trying to use: http://www.filedropper.com/icon_4

What could be the problem? Thanks.

**Comment by maxogden** [comment]
i'm not 100% sure on this but try an `.icns` file rather than a `.ico`

**Comment by oleander** [comment]
That solved the problem. Thanks. I used this online tool to convert the icon. https://iconverticons.com/online/
