### ISSUE TITLE
Self signed certificate in chain

### ISSUE THREAD

**Issue by ngreco** [maxogden/electron-packager#190]
When attempting to use electron-packager, I receive an error:
```
Error: self signed certificate in chain
```
I receive this error because the network at work intercepts traffic for security reasons and seems to disallow downloading files through means such as node-gyp or whatever electron-packager is using.

I had this problem when first learning how to create node addons for Electron apps, which I worked around by being able to download Electron headers and pointing node-gyp to these headers.

As far as I can tell, there is no way to currently tell electron-packager where the Electron headers are located so that it can run without the self signed certificate error. Are there plans for such functionality?

**Comment by malept** [comment]
I assume this happens when it tries to download the prebuilt electron binaries?

**Comment by ngreco** [comment]
That's what it looks like. I have prebuilt binaries downloaded already, which I'd love to point to instead of it trying to download them anyway.

**Comment by malept** [comment]
Did you try setting the [`--cache`](https://github.com/maxogden/electron-packager/blob/master/usage.txt) parameter?

**Comment by ngreco** [comment]
I tried that and I get the same problem with the self-signed certificate in chain.
I am calling electron-packager as such:
```
electron-packager . RedBook --platform=win32 --arch=x64 --version=0.34.0 --cache="c:\users\greco\documents\electron0.34.0"
```

**Comment by malept** [comment]
Just to be thorough, I assume the file `electron-v0.34.0-win32-x64.zip` exists in that cache directory?

**Comment by ngreco** [comment]
It is unzipped there. It should be still in .zip form?

**Comment by ngreco** [comment]
Pointed cache to the folder containing the .zip file. It now works without the self signed certificate errors.
Thank you for your help! That list of flags was a little confusing.
