### ISSUE TITLE
Icon not being added to .exe file

### ISSUE THREAD

**Issue by jviotti** [maxogden/electron-packager#193]
Hi,

I'm packaging an application with `electron-packager@5.1.1` on OS X El Capitan with the following command:

```sh
electron-packager . Herostratus \
	--platform=win32 \
	--arch=x64 \
	--version=0.34.2 \	
        --icon="assets/icon.ico" \
	--overwrite \
	--out=release/
```

The icon is added to the top left corner of the window and appears in the bottom bar on Windows 10, however I still see the default Electron icon when opening the directory with the file explorer.

Is there anything else I have to add to get the icon on the `.exe` file?

I also tested generating the package directly on Windows 10 in case the issue was `wine`-related but the results were the same.

**Comment by malept** [comment]
Perhaps it's because you don't have the appropriate icon size for the file explorer in your icon file?

**Comment by jviotti** [comment]
@malept Sounds like that's the problem. Turns out my icon size is 16x16. What's the expected side? I can't find any documentation on the README.

**Comment by malept** [comment]
I don't know offhand, I would look in the MSDN documentation. Personally, I just [generate a whole bunch of common icon sizes](https://github.com/malept/gmusicprocurator-app/blob/master/Makefile) in order to create the ICO and ICNS files for my app.

**Comment by jviotti** [comment]
I have a multi-layered ico with the following sizes that still doesn't work:

- 16x16
- 32x32
- 48x48
- 64x64
- 128x128
- 256x256

**Comment by jviotti** [comment]
I did two things and one of them solved the issue, but not sure which one:

- I had a 1024x1024 *.png icon that I passed to `BrowserWindow`. I resized to `256x256`.
- Pass `--asar` to `electron-packager`.

**Comment by nirmohiofficials** [comment]
i tried with --icon="./assets/icon.ico" 
this works for me

**Comment by alex-lushiku** [comment]
> I did two things and one of them solved the issue, but not sure which one:
> 
> * I had a 1024x1024 *.png icon that I passed to `BrowserWindow`. I resized to `256x256`.
> * Pass `--asar` to `electron-packager`.

The second

**Comment by malept** [comment]
Passing `--asar` has zero impact on the icon embedded in the Windows executable.

**Comment by actualdankcoder** [comment]
first one turned out to be the solution for me

**Comment by gfmoore** [comment]
Nope nothing is working. I mean how hard can it be... :(
