### ISSUE TITLE
Download links?

### ISSUE THREAD

**Issue by sapioit** [maxogden/electron-packager#196]
Hello,

Are you using code for automaticly fetching the list of download links for binaries? If not, how are you getting the list of versions needed and the download links? Oh, and how could i run this thing in Windows?

**Comment by maxogden** [comment]
For downloading Electronbinaries it uses http://github.com/maxogden/electron-download

To use it on Windows you can use either the command-line or JS APIs mentioned in the readme

**Comment by sapioit** [comment]
Thanks!
