### ISSUE TITLE
Unhide the menu bar at top.

### ISSUE THREAD

**Issue by ahgan84** [maxogden/electron-packager#199]
Hi guys, I notice that electron-packager has hide the top menu bar after we compiled an exe file. Is there ways to unhide it? I need to use it for user to choose some settings.

**Comment by malept** [comment]
I just ran into this, and I think electron-packager is doing the right thing. (Though, I don't actually think electron-packager is *doing* anything to hide the menu...) What you need to do is specify menus via the [Menu API](http://electron.atom.io/docs/v0.36.0/api/menu/).
