### ISSUE TITLE
application icon not changed for windows buildings

### ISSUE THREAD

**Issue by plrthink** [maxogden/electron-packager#201]
I am using electron-packager v5.1.1 with electron v0.35.0 on windows 10. I passed a icon path string to electron-packager and the icon of exe file doesn't changed. But when I run the exe the title icon of electron window has already been changed. 

I think I have the right icon file for windows as 256 * 256 with icon extension.

**Comment by plrthink** [comment]
It seems like something wrong with vs2015, after I changing to vs2013 as electron docs says it works fine.

**Comment by SamvelRaja** [comment]
Still for me the icon is not changing in windows build. I am passing the option through cmd line as --icon
Is there any condition for the location of icon?

**Comment by mattkenefick** [comment]
+1
