### ISSUE TITLE
Add configurable option for the temp build directory

### ISSUE THREAD

**Issue by bitwombat** [maxogden/electron-packager#203]
Using this command line:

    $ electron-packager . UF --platform=win32 --overwrite --arch=ia32 --version=0.34.2

My app builds just fine if I executed on a subset of it (e.g. 2 of 41 chapters of an educational resource).

However, a full build fails silently (20G of product, most of that videos).

Nervous about shipping product in 2 weeks... so close to working!

How do I debug this?

**Comment by bitwombat** [comment]
<Light bulb>
So electron builds everything in /tmp, eh?  Which is tmpfs on my system, so I was running out of space.  So that my premature greying slows down a bit, could there be an error to this effect please?

**Comment by malept** [comment]
The failure message should come from one of our upstream libraries, I think in this case it's `ncp`. However, we've found that there are several edge cases that it triggers, probably including the one you found. #151 proposes to replace that library.

It shouldn't be hard to change electron-packager to make the base temporary location a configurable option. Search for references to `temp` or `tmp` in `index.js`.

**Comment by bitwombat** [comment]
Oh, beautiful.

electron-packager uses os.tmpdir() which, if I look at `/usr/lib/nodejs/os.js` I can see is:

    exports.tmpdir = function() {
      return process.env.TMPDIR ||
             process.env.TMP ||
             process.env.TEMP ||
             (process.platform === 'win32' ? 'c:\\windows\\temp' : '/tmp');
    };

So all I need to do is set TMPDIR (or TMP or TEMP) in my shell's environment before calling node-packager.  Long live open source!

**Comment by eugirdor** [comment]
I would find being able to specify a custom temp build directory helpful as well.  I am trying to run multiple builds in parallel, but it fails because they all try to write into the same temp directory.

**Comment by malept** [comment]
@eugirdor https://github.com/maxogden/electron-packager/issues/203#issuecomment-158686024 mentions three environment variables that you can set in your build script in the meantime.

**Comment by eugirdor** [comment]
@malept I am using that for now, but it only works when using the command line (or via spawn).

I have not found a workaround if you are using the programmatic interface:

`var packager = require('electron-packager')`

**Comment by malept** [comment]
@eugirdor setting `process.env.TMPDIR`, for example, did not work for you?

**Comment by eugirdor** [comment]
@malept The problem is that is global, so all parallel builds will end up using the last set value.  I should have a pull request soon that adds the configurable switch.  Just testing it out now.
