### ISSUE TITLE
5.1.1 missing asar-unpack-dir, release 5.2.0

### ISSUE THREAD

**Issue by EragonJ** [maxogden/electron-packager#204]
I noticed that 5.1.1 miss the patch @hokein provided for `asar-unpack-dir`.

From the commit (https://github.com/maxogden/electron-packager/commit/5a967c697794bb7d42168a96af15c7d65f2e4a27#diff-b9cfc7f2cdf78a7f4b91a753d10865a2L20) which bumped the version to 5.1.1, its `asar` dependency still points to `0.6.1` instead of `0.8.2` here (https://github.com/maxogden/electron-packager/commit/132c21471bdcefdfa83cccfef5863e5ec0ded03c )

I thought there might be some problems when publishing 5.1.1 and it let the commit lost. And also, because latest version in npm still points to 5.1.1, any user trying to `npm install electron-packager` will have no way to use this newly introduced `asar-unpack-dir`.

For my personal project, I need to revise `package.json` by myself to force it point to `maxogden/electron-packager` to get it working. No matter how, I think the better way here is to bump the version to `5.1.2` (there is no critical change after `asar-unpack-dir` patch, so I think this is fine) 

Hope this information helps !

**Comment by EragonJ** [comment]
If you need any help, feel free to tag me by the way !

**Comment by tsamsonbm** [comment]
This seems like a really simple, useful fix.  I was jut about to put in a ticket for asar-unpack-dir not working.

**Comment by maxogden** [comment]
oh yea looks like we havent published in 2 months, oops. looking into it now

**Comment by maxogden** [comment]
5.2.0 is out!

p.s. if any other collaborators want npm publish access, lemme know

**Comment by EragonJ** [comment]
:+1:
