### ISSUE TITLE
"A JavaScript error occurred in the main process" running app on OSX that was packaged on Linux

### ISSUE THREAD

**Issue by bitwombat** [maxogden/electron-packager#205]
When I package an app for OSX on Linux, on Launch I get the error in the subject (details below)

If I run electron on the source on the mac, it's fine.

*    Which version of electron-packager are you using?
    5.1.1

*    What cli arguments are you passing?
    `electron-packager . UF --platform=darwin --arch=x64 --version=0.34.2 --overwrite`

*    What platform are you running electron-packager on?
    Ubuntu 14.04.01 LTS (32-bit)

*    What platform(s) are you building for?
    OSX 10.10.5

*    Is there a stack trace in the error message you're seeing?
    No error on run of electron-packager.
    Error when launching application on OSX:
```
    A JavaScript error occurred in the main process

    Uncaught Exception:
    Error: Cannot find module 'electron'
        at Function.Module._resolveFilename (module.js:336:15)
        at Function.Module._load (module.js:286:25)
        at Module.require (module.js:365:17)
        at require (module.js:384:17)
        at Object.<anonymous> (/Volumes/iOS_apps/electron/UF.trimmed/UF-trimmed-darwin-x64/UF-trimmed.app/Contents/Resources/app/src/main.js:151:14)
        at Module._compile (module.js:434:26)
        at Object.Module._extensions..js (module.js:452:10)
        at Module.load (module.js:355:32)
        at Function.Module._load (module.js:310:12)
        at Object.<anonymous> (/Volumes/iOS_apps/electron/UF.trimmed/UF-trimmed-darwin-x64/UF-trimmed.app/Contents/Resources/atom.asar/browser/lib/init.js:123:10)
```

## How to reproduce using generated binary
*On OSX:*
* Download and unzip [UF.zip](https://www.dropbox.com/s/qs824nubigwnckg/UF.zip?dl=0)
* In Finder, navigate to the UF-trimmed-darwin-x64 folder
* Double-click on UF-trimmed.app
* See above error dialog

## How to reproduce from source
*On Ubuntu 14.04 LTS*
* Download and unzip [UF.src.zip](https://dl.dropboxusercontent.com/u/17914213/UF.src.zip)
* cd UF.trimmed.src
* run `electron-packager . UF.trimmed --platform=darwin --arch=x64 --version=0.34.2 --overwrite`
* In Finder, navigate to UF.trimmed.src/UF-trimmed-darwin-x64
* Double-click on UF-trimmed.app
* See above error dialog

**Comment by herrmannplatz** [comment]
I think electron module was introduces in version (0.35.0)[https://github.com/atom/electron/releases/tag/v0.35.0]

**Comment by bitwombat** [comment]
Upgrading did the trick.  Thanks.  Should electron-packager have warned me about this?

**Comment by malept** [comment]
>  Should electron-packager have warned me about this?

IMO, no. That would require electron-packager to scan your source code (and possibly, any of your dependencies) for references to `require('electron')`, which is a very difficult problem to solve with many edge cases.

**Comment by bitwombat** [comment]
But doesn't everything that electron-packager packages require electron?  I'm a n00b here, so excuse the ignorance.

**Comment by malept** [comment]
According to the 0.35.0 release notes (linked above), it was added in 0.35.0. Electron apps using earlier versions of Electron do not use the `require()`d module named `electron`. Instead, the modules such as `app` had to be `require()`d separately. Compare the `main.js` code in the [Electron 0.34.0](http://electron.atom.io/docs/v0.34.0/tutorial/quick-start/#write-your-first-electron-app) tutorial with the equivalent code in the [Electron 0.35.0](http://electron.atom.io/docs/v0.34.0/tutorial/quick-start/#write-your-first-electron-app) documentation.

**Comment by bitwombat** [comment]
Right, so I guess my point is that electron-packager could have saved me all the head-scratching, testcase generation, and debug, and saved both of us this conversation by saying "You don't want to be using that version, dumbass".

Instead I had an app that worked fine with electron, but not fine once packaged.  Think of it from the 'dumb user' standpoint here.

**Comment by bitwombat** [comment]
Wait, what happened is that my main.js, copied from the docs, is what's requiring electron.... so, I'm at a loss here for how we could have prevented this whole thing.

So, user error?  I was looking at a doc version (with stock main.js) different than my installed version?

**Comment by malept** [comment]
> So, user error? I was looking at a doc version (with stock main.js) different than my installed version?

Yeah, basically. It's one of the hazards of using a pre-1.0 library/application that uses semantic versioning. I'm specifically referring to Electron, but it also applies to electron-packager.

> I'm at a loss here for how we could have prevented this whole thing.

So, we *could* do what you suggest and add a feature to detect whether you can use a certain API structure with a given Electron version If we ignore how complex a solution would be, I don't think it fits within electron-packager. I think it would be more of an "electron-lint" sort of project. If that doesn't make any sense, I'm talking about a hypothetical tool in the style of [`eslint`](https://github.com/eslint/eslint) that would tell you problems about your Electron-specific code, given a target Electron version. Perhaps since `eslint` has the concept of "pluggable rules", it would make sense to write an `eslint` rule for this.

**Comment by malept** [comment]
@reach2jeyan since this is a 2+ year old issue, you're better off asking your question (with a small, clear, reproducible testcase) in one of the [community forums](https://electronjs.org/community).
