### ISSUE TITLE
Unsupported arch. Must be either ia32 or x64

### ISSUE THREAD

**Issue by bitomule** [maxogden/electron-packager#208]
Trying to build all architectures for osx and I get this error:

```
Unsupported arch. Must be either ia32 or x64
```

It was working until I updated electron to 0.35. Works if I set arch to x64.

**Comment by malept** [comment]
Could you please provide us with more information about your environment and steps to reproduce, per the [contributing docs](https://github.com/maxogden/electron-packager/blob/master/CONTRIBUTING.md)? It will help with figuring out what the issue may be.

With the given information, I cannot reproduce this (electron-packager 5.1.1 running on Linux) using this command line:

```sh
node_modules/.bin/electron-packager src Test --platform=darwin --arch=all --out=/tmp/test --version=0.35.0
```

**Comment by bitomule** [comment]
I think it was some kind of error in my setup. Removed node_modules folder and installed again. That fixed it.
