### ISSUE TITLE
Is it required to distribute the license/version file with the app?

### ISSUE THREAD

**Issue by wearhere** [maxogden/electron-packager#210]
As described in the README, the output directory (at least on OS X) looks like:

```
FooBar-darwin-x64
├┬FooBar.app
 └[…Mac app contents…]
├─LICENSE
└─version
```

Is it required to include the `LICENSE` and `version` files? My feeling is that it would be a simpler user experience to receive a directory containing _just_ the `.app`.

**Comment by malept** [comment]
You need to distribute the license (in some form), per the terms of Electron's license.

I don't know about `version`, it's helpful for debugging purposes. I am not aware of a technical reason to distribute it.

**Comment by wearhere** [comment]
Ok, thanks!

**Comment by wearhere** [comment]
@malept would you be able to point me to where 

> You need to distribute the license (in some form), per the terms of Electron's license.

is stated? I don't see it noted in their [distribution docs](https://github.com/atom/electron/blob/master/docs/tutorial/application-distribution.md), [README](https://github.com/atom/electron/blob/master/README.md), or [LICENSE](https://github.com/atom/electron/blob/master/LICENSE).

**Comment by malept** [comment]
> The above copyright notice and this permission notice shall be
> included in all copies or substantial portions of the Software.

From: https://github.com/atom/electron/blob/f176b2c58f0a65f796053c2a25250ab17dfd3649/LICENSE#L11-L12

**Comment by wearhere** [comment]
Ah I see. I was a bit confused about whether that needed to be shown to the enduser or just included in the source… What about the Chromium licenses? I also see a `LICENSES.chromium.html` in the output directory.

**Comment by malept** [comment]
Electron is built on Chromium, so I imagine so.

**Comment by wearhere** [comment]
:ok_hand:
