### ISSUE TITLE
OS X package: Fatal error: Cannot read property 'message' of undefined

### ISSUE THREAD

**Issue by xionglun** [maxogden/electron-packager#214]
packager at windows is ok, but at Mac OS X 10.11.1, it failed:
> Running "packager" task
> Packaging app for platform darwin x64 using electron v0.35.4
> Fatal error: Cannot read property 'message' of undefined

**Comment by malept** [comment]
Per our [contributing instructions](https://github.com/maxogden/electron-packager/blob/master/CONTRIBUTING.md):
> Please provide all of the following information:
>
> * Which version of electron-packager are you using?
> * What cli arguments are you passing?
> * What platform are you running electron-packager on?
> * Is there a stack trace in the error message you're seeing?
> * If possible, please provide instructions to reproduce your problem

Thanks!

**Comment by xionglun** [comment]
Sorry, I have found out the problem.
My app's `node_modules` folder has some broken links, it cause an error:
> Error: ENOENT: no such file or directory
> errno: -2
> code: 'ENOENT'
> syscall: 'stat'
> path: '/Users/***/app/node_modules/.bin/envify'
