### ISSUE TITLE
Cannot build on OSX 10.11.1

### ISSUE THREAD

**Issue by Davidaredding** [maxogden/electron-packager#216]
using electron-prebuilt

let the build sit for 30 minutes and no reports, gets stuck here.

$ electron-packager . FooBar --platform=darwin --arch=x64 --version=0.35.0
Packaging app for platform darwin x64 using electron v0.35.0

 EXPORT DEBUG=electron-download,extract-zip

stuck here building for darwin

extract-zip mkdirp +0ms { dir: '/var/folders/k7/tqx9n0_j53v2z5y2dz1nk0vm0000gn/T/electron-packager/darwin-x64-template/Electron.app/Contents/Resources/zh_TW.lproj/' }
extract-zip finished processing +0ms Electron.app/Contents/Resources/zh_TW.lproj/ { err: undefined }
extract-zip zip extraction complete +0ms

stuck here building for linux

extract-zip mkdirp +0ms { dir: '/var/folders/k7/tqx9n0_j53v2z5y2dz1nk0vm0000gn/T/electron-packager/linux-x64-template/locales' }
extract-zip opening read stream +0ms /var/folders/k7/tqx9n0_j53v2z5y2dz1nk0vm0000gn/T/electron-packager/linux-x64-template/locales/ta.pak
extract-zip finished processing +1ms locales/ta.pak { err: undefined }
extract-zip zip extraction complete +0ms

this was mentioned in the previous thread about delayed building but the thread seems to have died at "needs info".

**Comment by malept** [comment]
I'm not sure how this is different from #213.

**Comment by Davidaredding** [comment]
It's not, but that thread is dead waiting on op to deliver More Information.

**Comment by malept** [comment]
I'd rather not have multiple issues open about the same problem. Feel free to continue commenting on #213 if you have further information to share (for example, investigating whether Max's guess is accurate or not).

**Comment by Davidaredding** [comment]
I'm not sure how his guess helps find a solution or work around.

**Comment by malept** [comment]
If his guess proves to be accurate, then we at least have a reason why it's happening. That will go a long way towards a solution. (Indeed, #151 would be one potential solution.)

Anyway, as I said in my earlier comment, that was just one example.
