### ISSUE TITLE
Option to ignore "devDependencies" and the dependencies they generate.

### ISSUE THREAD

**Issue by jamen** [maxogden/electron-packager#221]
It is advised in this project's README that you should ignore packages that aren't used in production.  Packages that aren't used in production are most commonly associated with the `"devDependencies"` in a project's `package.json` file.  It would be cool if there was a system to automatically ignore those dependencies with an option like `--ignore-dev`.

However, a problem arises when `devDependencies` have dependencies of their own...  And since npm produces a flat `node_modules`, you would have to see what packages in `node_modules` are are used by `"dependencies"` instead (and their dependencies, and their dependencies, and their dependencies, ... recursively).  If you find any packages not listed in the product, then they are `"devDependencies"` or the like.

**Comment by jamen** [comment]
Oh wait, silly me...

I could use `--ignore="node_modules"` then use `npm install --production` on the generated package.

**Comment by jamen** [comment]
I still think there should be a `--ignore-dev` though, that implements what I said above automatically.

**Comment by maxogden** [comment]
:)

**Comment by cawa-93** [comment]
@jamen Could you give some examples?  I can't imagine how to solve this problem in the way you described.

**Comment by malept** [comment]
This is enabled in Electron Packager by default.

If you need more assistance, please use one of the [community forums](https://electronjs.org/community), including the [Electron Discord server](https://discord.gg/electron).
