### ISSUE TITLE
How do I specifiy icons when building for multipl platforms?

### ISSUE THREAD

**Issue by rdbell** [maxogden/electron-packager#222]
I'm using --platform=darwin,win32

darwin requires icns file, win32 requires ico.

It seems like the --icon= parameter only accepts one value. How do I specify icons for both platforms?

Do I need to separate my build into two commands?

**Comment by kfranqueiro** [comment]
Just leave off the file extension in the option and it'll resolve it for you, per-platform.

From the README:

> If the file extension is omitted, it is auto-completed to the correct extension based on the platform, including when `--platform=all` is in effect.

**Comment by rdbell** [comment]
Ah, sorry! Not sure how I missed that in the README.

Thanks!
