### ISSUE TITLE
On OS X, wrong icon displayed in the Dock

### ISSUE THREAD

**Issue by kdawg1406** [maxogden/electron-packager#225]
UPDATE & SOLVED -  Found the problem.  The source image I used to create the .icns file was 1024x1024.  I resized the source to 512x512 and rebuilt my Electron app.  The correct app appeared.

I know this sounds crazy, but the wrong icon is displayed in the OS X Dock when I run my app.

In Finder, my app has the wrong icon.  Looks like a piece of paper with a ruler, pencil and brush.

However, if I view my app's "Package Contents", go the Resources folder, the atom.icns is my icon.  I can open it using the Preview app.

Any idea why the atom.icns file in the Resources folder is not being used by OS X for the Finder app icon and the Dock icon?

Thank you,

Karl

**Comment by btelintelo** [comment]
Wow we had the same issue and was on rabbit chase until I found this!  Our icon 1024x1024 was working on retina displays but would break on others.  Thank you for posting this.

**Comment by develar** [comment]
It seems your ICNS is invalid or your icns app maker is not good. My source icon is 1024 and it works on retina and non-retina iMac. Consider using http://www.img2icnsapp.com app.

Could you please send me or attach here your ICNS files? So I can check it and validation? (I am electron-builder maintainer and I think that it will be cool if electron-packager will check such errors and report).

**Comment by malept** [comment]
> I think that it will be cool if electron-packager will check such errors and report

I would like to note that if electron-packager were to do that, I would prefer to see the icon checker code for that in a separate module (because that's certainly not an electron-packager specific function), and then we would integrate that module into the current icon code.

**Comment by btelintelo** [comment]
Just change extension from png to icns
![icon icns](https://cloud.githubusercontent.com/assets/3678777/14741144/469ac66a-0862-11e6-9cb8-f3f4151e2df7.png)
