### ISSUE TITLE
Setting the path of Electron.app for electron-packager

### ISSUE THREAD

**Issue by maxogden** [maxogden/electron-packager#23]
question from @rv2358:

Hi,
I installed Electron with npm. I now want to check in the Electron.app (with modifications to icon, name etc) into git. So I made a copy of Electron.app in another dir. How do i get electron-packager to use the Electron.app in my git directory vs the one in /usr/local/bin/node_modules/electron-prebuilt ?
Thanks

**Comment by maxogden** [comment]
@rv2358 right now electron-packager doesnt have an option for using a different source app than the one that is distributed inside the official electron releases, so it would take modifications to the code to support that. However, if you are just modifying the name and icon you can do that by specifying the correct command line options to electron-packager

**Comment by jrudio** [comment]
Hi @maxogden, 
  This seems to be relatively easy right? I would like to use electron-packager in my meteor package, but as you have said it uses the npm pre-built binary, whereas I would need it to use the unzipped version of electron.So I would just need to add a way to supply the path to of my unzipped electron to electron-packager?

**Comment by maxogden** [comment]
@jrudio I dont fully know the reasons *why* you need to use a custom version of the electron zipfile that you modified, but if you are sure you have a good reason to require a custom extracted + modified version of electron (which you downloaded from the same place that `electron-packager` downloads its releases), then it shouldn't be too much work if you have experience doing work on node.js modules. You would basically need to add a new command-line option that lets a user specify the electron template folder, e.g. `--electron-template=./MyCustomElectron/` and then change the code to use that directory instead of the default method (which is to download a zip from electron and unzip it).

The tricky part of this is that we recently added linux and windows support, and you'd have to make sure your change works with those systems as well, which could be tricky given the project is currently moving pretty quickly.

**Comment by jrudio** [comment]
Haha I thank you for pointing it out. You convinced me I do not need to use the zipped up version. I guess I was stuck on that idea because of a boilerplate I ran across that used the zipped version, and I believed that it was the best solution. So, yeah, my idea was flawed. Thanks for the response, and good stuff on the windows support!

**Comment by maxogden** [comment]
@jrudio glad you were able to sort it out, and thanks

**Comment by rv2358** [comment]
Thanks for the response.

**Comment by D6NK** [comment]
okay but i can compile because there is a space in the name of some part of my directory. any ideas?

**Comment by D6NK** [comment]
cant*
