### ISSUE TITLE
Update CONTRIBUTING.md to document how PRs work

### ISSUE THREAD

**Issue by malept** [maxogden/electron-packager#231]
This is mostly a TODO for myself, but feedback is appreciated. Or, if someone else gets to it before me, even better!

Things to mention (in no particular order):

* [x] Add tests when necessary (document when "necessary" is)
* [x] Add docs when necessary (document when "necessary" is)
* [x] Note which coding standard is used
* [x] Make sure all tests pass
* [x] Git rebasing, etc.

**Comment by maxogden** [comment]
nice, we should update https://github.com/openopensource/openopensource.github.io
