### ISSUE TITLE
Child process output issue for certain cli commands

### ISSUE THREAD

**Issue by otakustay** [maxogden/electron-packager#232]
### Environment

- electron-packager `5.2.0`
- electron `0.35.4` (Problem exists also in `0.36.1`)
- command `electron-packager . Electron-Issue --platform=darwin --arch=x64 --version=0.35.4 --out=releases --overwrite`
- OS X 10.11.2

### Introduction to issue

This is a weird issue, I have tried my best but failed to find any solution.

The issue can be reproduced when **ALL** conditions below matches:

1. Use `child_process` module to execute `unrar` cli tool viewing files of a rar file
2. The rar file has a file whose name contains  non-ASCII character, in my case I have some chinese characters
3. The app is packaged with `electron-packager`

The code is simple as `main.js` is:

```js
'use strict';

let electron = require('electron');
let app = electron.app;

let start = () => {
    let BrowserWindow = electron.BrowserWindow;
    let mainWindow = new BrowserWindow({width: 800, height: 600});

    let url = 'file://' + require('path').join(__dirname, 'index.html');
    mainWindow.loadURL(url);
};

app.on('ready', start);
app.on('window-all-closed', () => app.quit());
```

And my `index.html` is:

```html
<!DOCTYPE html>
<html>
<head>
    <meta charse="utf-8" />
    <title>Electron Issue</title>
</head>
<body>
    <h2>Command</h2>
    <pre><code>./unrar lb ./Archive.rar</code></pre>
    <h2>Output</h2>
    <pre id="output"></pre>
    <script>
        'use strict';

        try {
            let command = require('path').join(__dirname, 'unrar');
            let archive = require('path').join(__dirname, 'Archive.rar');
            let s = require('child_process').execSync(`${command} lb ${archive}`);
            document.getElementById('output').innerText = s;
        }
        catch (ex) {
            document.getElementById('output').innerText = ex;
        }
    </script>
</body>
</html>
```

### Execute in command line

When the command is executed in terminal directly, it's output is correct:

```shell
~ unrar lb Archive.rar

abc测试1.png
bar中文.png
foo有标点，奇怪的东西.png
xyz试试.png
```

### Run via electron

When run the app use `electron Electron-Issue.app/Contents/Resources/app/` to start the app, it gives correct output:

```
Command

./unrar lb ./Archive.rar
Output

abc测试1.png
bar中文.png
foo有标点，奇怪的东西.png
xyz试试.png
```

### Run app

When doubleclick the `Electron-Issue.app`, it gives incorrect output:

```
Command

./unrar lb ./Archive.rar
Output

abcbarfooxyz
```

We can see just leading ASCII characters are printed, is seems for each filename, the output is missing when the first non-ASCII character is encountered, and the trailing `\n` is also missing.

### Other case

If the command is not `unrar lb`, the output is correct, e.g. `ls .` give correct output even we have files with non-ASCII name.

so I don't know if this is an issue of `electron`, `electron-packager` or `unrar` cli, or how can I find where the problem sits.

I can upload the packaged app (112MB) if needed.

**Comment by maxogden** [comment]
Wow very odd. Thank you for the detailed debugging information. I am not sure how to proceed either, but perhaps someone else has an idea

**Comment by malept** [comment]
It seems like an encoding error of some sort (for example, `LC_ALL` gets set to `C`, which if I remember correctly means ASCII). Apart from testing whether setting various locale-related environment variables to the appropriate value changes the behavior, I'm not sure how to proceed either.

**Comment by otakustay** [comment]
Thanks @malept , it is actually the case of locale, I tried to change command to:

```shell
export LC_ALL=zh_CN.UTF-8 && export LANG=zh_CN.UTF-8 && unrar lb Archive.rar
```

Then the app runs perfectly

So it seems to be an issue with electron itself? or just the problem of `electron-packager` that did not package an app with the same locale of running os? If problem belongs to electron, we can close this issue :)

**Comment by otakustay** [comment]
The minimum command is:

```shell
export LANG=zh_CN && unbar lb Archive.rar
```

in which `zh_CN` is my system locale

The default output of `locale` in packaged app is:

```shell
LANG=
LC_COLLATE="C"
LC_CTYPE="C"
LC_MESSAGES="C"
LC_MONETARY="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_ALL=
```

**Comment by malept** [comment]
It seems to me that what you want is the environment that calls `unrar` to inherit from the parent environment. See if you can pass in `process.env` (I think that's the name in Node) as an env(ironment) parameter to `child_process` or one of its functions. If that works, then it's not really a bug in electron-packager.

**Comment by otakustay** [comment]
Just use `{env: process.env}` as `options` parameter of `execSync` function do not resolve this issue:

```js
// Still with problem
let s = require('child_process').execSync('unrar lb Archive.rar', {env: process.env});
```

Here is a dump of `process.env` object:

```json
{
    "TMPDIR": "/var/folders/pw/yfdnt2s136l9s6_w2kwghzqm0000gn/T/",
    "__CF_USER_TEXT_ENCODING": "0x1F5:0x19:0x34",
    "SHELL": "/bin/zsh",
    "HOME": "/Users/otakustay",
    "Apple_PubSub_Socket_Render": "/private/tmp/com.apple.launchd.vveKMvObNq/Render",
    "SSH_AUTH_SOCK": "/private/tmp/com.apple.launchd.9NUkEfFeYR/Listeners",
    "PATH": "/usr/bin:/bin:/usr/sbin:/sbin",
    "LOGNAME": "otakustay",
    "XPC_SERVICE_NAME": "0",
    "USER": "otakustay",
    "XPC_FLAGS": "0x0",
    "GOOGLE_API_KEY": "***"
}
```

Seems no locale related properties there, compared to the one when app is started with `electron .`:

```son
{
    "PATH": "/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin",
    "TMPDIR": "/var/folders/pw/yfdnt2s136l9s6_w2kwghzqm0000gn/T/",
    "LOGNAME": "otakustay",
    "XPC_FLAGS": "0x0",
    "HOME": "/Users/otakustay",
    "Apple_PubSub_Socket_Render": "/private/tmp/com.apple.launchd.vveKMvObNq/Render",
    "LANG": "zh_CN.UTF-8",
    "COLORFGBG": "7;0",
    "USER": "otakustay",
    "SSH_AUTH_SOCK": "/private/tmp/com.apple.launchd.9NUkEfFeYR/Listeners",
    "TERM": "xterm-256color",
    "ITERM_PROFILE": "Hotkey Window",
    "TERM_PROGRAM": "iTerm.app",
    "XPC_SERVICE_NAME": "0",
    "SHELL": "/bin/zsh",
    "ITERM_SESSION_ID": "w0t2p1:E2B1EE5A-8296-451D-913E-AF33A18F8A11",
    "PWD": "/Users/otakustay/Dev/electron-bug",
    "__CF_USER_TEXT_ENCODING": "0x1F5:0x19:0x34",
    "SHLVL": "1",
    "OLDPWD": "/Users/otakustay/Dev",
    "ZSH": "/Users/otakustay/.oh-my-zsh",
    "PAGER": "less",
    "LESS": "-R",
    "LC_CTYPE": "zh_CN.UTF-8",
    "LSCOLORS": "Gxfxcxdxbxegedabagacad",
    "AUTOJUMP_SOURCED": "1",
    "AUTOJUMP_ERROR_PATH": "/Users/otakustay/Library/autojump/errors.log",
    "_": "/usr/local/bin/electron",
    "GOOGLE_API_KEY": "***"
}
```

Many things are missing in packaged app.

**Comment by malept** [comment]
How are you executing the packaged app? Double-clicking it in Finder, or executing it on the command line?

**Comment by otakustay** [comment]
By double-clicking it

**Comment by malept** [comment]
I think what's happening is that the OSX non-terminal environment is not setting the environment variables that you need for `unrar` to display properly. You're going to have to figure out how to determine the correct language some other way (another node package?) and then set them yourself as you did in https://github.com/maxogden/electron-packager/issues/232#issuecomment-169980736.

Given that, I don't think this is a bug in electron-packager.

**Comment by otakustay** [comment]
OK, I'll try to determine system env variables, thanks for hints, closing this:)
