### ISSUE TITLE
ASAR does not include dotfiles

### ISSUE THREAD

**Issue by quicksnap** [maxogden/electron-packager#234]
When using the `asar` option to package my application, it is not packaging dotfiles in the resulting `app.asar` file. Using `asar list |grep .myDotFile` yields nothing. When using `asar` to manually package my directory which contains dotfiles, it works just fine.

Is this an issue with `ncp`? Maybe this line? https://github.com/maxogden/electron-packager/blob/master/common.js#L83

Sorry I haven't yet dug into it; I'm hoping someone might have a good idea. I'll probably be cracking it open soon to see what's up, and maybe get a PR.

> Which version of electron-packager are you using?

5.2.0

> What cli arguments are you passing?

```js
packager({
    dir: getBuildPath(),
    ignore: null, 
    asar: true,
    name: 'My App',
    platform: [ process.platform ],
    arch: 'x64',
    version: ELECTRON_VERSION,
    out: `${getBuildPath()}/dist`,
    overwrite: true,
  }, (err, appPath) => {
    if (err) {
      console.log('Something went wrong..', err);
      process.exit(1);
    }
  });
```

> What platform are you running electron-packager on? What platform(s) are you building for?

OSX 

> Is there a stack trace in the error message you're seeing?

Nope. The resulting ASAR simply doesn't contain dotfiles.

**Comment by malept** [comment]
Try without the `asar` parameter to see if the dotfiles get copied to the `out` directory. If they do, it seems like a bug in the asar module (or electron-packager's code dealing with asar).

**Comment by quicksnap** [comment]
@malept With `asar` set to false, it does copy the dotfile.

**Comment by quicksnap** [comment]
I ran a test with NCP and that seems not to be the problem. I'll experiment with the asar module.

**Comment by quicksnap** [comment]
I ran a minimal test with electron-packager and I think this is my own bug somehow. I'll check more things on my end. Sorry for taking up your time! Thanks, though.
