### ISSUE TITLE
Windows packager does not work

### ISSUE THREAD

**Issue by moazam1** [maxogden/electron-packager#236]
I am using windows 7 and latest electron version. I am using following command to build a package

    electron-packager . MyApp--platform=win32 --arch=ia32 --version=0.1

and here is the error I am getting:

	Downloading electron-v0.1-win32-ia32.zip
	Error: GET https://github.com/atom/electron/releases/download/v0.1/electron-v0.1-win32-ia32.zip returned 404
	[ [Error: GET https://github.com/atom/electron/releases/download/v0.1/electron-v0.1-win32-ia32.zip returned 404] ] undefined

I have checked electron repo and I couldn't found releases folder. Is there a quick fix available for this issue?

**Comment by malept** [comment]
Per the parameter documentation:

> `version` - *String*
>
> Electron version (without the 'v') - for example, `0.33.9`. See [Electron releases](https://github.com/atom/electron/releases) for valid versions.

You specified `--version=0.1`, and there isn't an Electron release tagged `0.1`. What you probably want is `--app-version=0.1`. (You still have to specify which Electron version you want to build against.)

**Comment by moazam1** [comment]
My bad. I thought `--version` is for my app
