### ISSUE TITLE
question: support for Electron env vars

### ISSUE THREAD

**Issue by rishson** [maxogden/electron-packager#238]
Hi. I have noticed different behaviour when running electron locally, and when running a packaged electron app. Specifically, env vars passed to the electron process don't seem to work in a packaged app. For example, if I build for darwin, then `Electron` executable in `MacOS` does not behave as a locally installed electron executable.

```
>ELECTRON_RUN_AS_NODE=true electron -v
```
will correctly outputs the node version. But this does not work when you have build an app using electronPackager:
```
>ELECTRON_RUN_AS_NODE=true dist/darwin/MyApp-darwin-x64/MyApp.app/Contents/MacOS/Electron -v
```
which will run the default app.
Does electron-packager support env vars in this way?

Edited:
Some background: running the app `MyApp.app` works fine, but I also want to get access to the node executable from within my app from a script.

**Comment by malept** [comment]
I believe it runs the default app because you need to specify the app directory in the second command.

**Comment by rishson** [comment]
@malept yep - makes sense. However, I'm trying to get to the underlying node executable directly. I guess my question could also be phrased as "Where is the node executable in a packaged Electron app?" :-)

**Comment by malept** [comment]
Good question. It's actually more obvious in builds that are not targeted for OS X. When you target for Windows, there is a `node.dll` file in the package. When you target for Linux, there is a `libnode.so` in the package.

So the answer is, Electron is not packaged with a node executable. It is prebuilt, linked to a node library (I guess, statically, in the case of OS X).

**Comment by malept** [comment]
To your other question (how can I get the node version from a script), my guess is that you'll have to provide that functionality yourself via your app (and argument parsing).

**Comment by rishson** [comment]
@malept thanks for your help on this.
So on OSX, the node lib is `MyApp.app/Contents/Frameworks/Electron Framework.framework/Libraries/libnode.dylib` - equivalent to the `node.dll` on Win32 and `libnode.so` on Linux.

**Comment by ricmed205** [comment]
+1

EG: Electron supports passing flags to the JS-engine like:

`$ electron --js-flags="--harmony_proxies --harmony_collections" your-app`

Is this supported?

**Comment by malept** [comment]
> So on OSX, the node lib is `MyApp.app/Contents/Frameworks/Electron Framework.framework/Libraries/libnode.dylib`

Ah, OK. I thought that was weird that only OS X was linked statically. All I did was a quick `find` on my app's `out` directory.

**Comment by malept** [comment]
I wonder if this might be a more relevant question for https://github.com/mafintosh/electron-prebuilt.

**Comment by maxogden** [comment]
Best place to ask it is actually in this repo http://github.com/atom/electron, they are the ones who actually create the .app in the first place, we just unzip it from the zip they upload in their releases and modify it

**Comment by rishson** [comment]
thanks @maxogden - I'll raise there.

**Comment by rishson** [comment]
Actually @maxogden, the following works fine:
```
>npm i electron-prebuilt
>ELECTRON_RUN_AS_NODE=1 node_modules/electron-prebuilt/dist/Electron.app/Contents/MacOS/Electron -v
```

So if the actual .app is fine, then it must be something that happens after download.
I've tried performing the stuff my build does such as removal of `default_app` etc, but Electron still works as expected.
The only time that the env vars are ignored, is when running against the .app after running electron-packager.

**Comment by rishson** [comment]
Just a quick update:

I currently believe that the issue of not being able to pass env vars is introduced in `electron-packager`.

Prebuilt electron works fine:
```
>npm i electron-prebuilt
>ELECTRON_RUN_AS_NODE=1 node_modules/electron-prebuilt/dist/Electron.app/Contents/MacOS/Electron -v
>v5.1.1
```

Electron that has been through `electron-packager`:
```
>ELECTRON_RUN_AS_NODE=1 node_modules/electron-prebuilt/dist/Electron.app/Contents/MacOS/Electron -v
>v0.33.9
```
The `electron-packager` version seems to be ignoring the ELECTRON_RUN_AS_NODE flag. A call to electron with the flag set and no params should start the node interpreter, but instead, it launches the default app.
I think we can rule out `electron-download` as being a culprit, as its used successfully in `electron-prebuilt`.
