### ISSUE TITLE
Package with electron command line switches

### ISSUE THREAD

**Issue by rickmed** [maxogden/electron-packager#241]
EG: Electron supports passing flags to the JS-engine like:

`$ electron --js-flags="--harmony_proxies --harmony_collections" your-app`
https://github.com/atom/electron/blob/master/docs/api/chrome-command-line-switches.md

Can I package my app so that when executed (EG: .exe) it runs with the flags?

**Comment by malept** [comment]
As in, without using an application shortcut, or is that OK?

**Comment by ricmed205** [comment]
@malept can you please clarify?

**Comment by malept** [comment]
When you double-click on the `.exe` file, is it required that the flags be set? Or is it OK if, for example, you click on the app's entry in the Start Menu (or whatever it's called these days), the flags are set?

**Comment by ricmed205** [comment]
On the exe itself (I assume if it is on the exe itself it will be set when calling the .exe from a shortcut)

**Comment by malept** [comment]
I point out a difference because with a shortcut, you can specify parameters when you specify which `.exe` it points to.

That being said, I don't know if either method works. I would have to do a bit of testing in order to figure that out (similar to how #238 was worked through).

**Comment by rickmed** [comment]
@malept :+1:

**Comment by malept** [comment]
I'm marking this as an answered question because I have no idea how we would integrate support for this. My opinion is that it should be handled in something like electron-builder (link in readme), where shortcuts for the application can, in theory, be generated.

**Comment by inca** [comment]
This seems critical, b/c there is no other way to set `-js-flags` other than passing them to `electron` executable.

**Comment by malept** [comment]
10 minutes of searching in the Electron issue tracker for "js-flags" led me to this undocumented feature (which was released after this question was asked): https://github.com/electron/electron/pull/4447. Try that and let me know how it works.

**Comment by inca** [comment]
@malept Thanks for prompt reply! I'll give it a try shortly.

**Comment by inca** [comment]
Unfortunately, after few prompt attempts I was unable to make it work with flags passed via `package.json`. I abandoned this in favor of few more build steps.

Anyway, big thanks for your efforts!

**Comment by damianobarbati** [comment]
Did anyone solve this? How can we pass --harmony flag to electron when building?
