### ISSUE TITLE
How can I create self-contained executables in Windows and GNU/Linux?

### ISSUE THREAD

**Issue by jviotti** [maxogden/electron-packager#243]
Is there a way to create a self contained executable that includes all the files from the output directory in Windows and GNU/Linux?

**Comment by malept** [comment]
This is not currently a feature of electron-packager. (Even for Mac apps, they're not technically "self contained executables", it's a special folder.)

That being said, if someone creates a Node module that transforms an Electron-based app into a self-contained executable, we would be open to adding integration via an optional parameter.

**Comment by malept** [comment]
Here's the answer the Electron people gave a while ago: https://github.com/atom/electron/issues/914

**Comment by jviotti** [comment]
@malept Thank you very much to the link!

**Comment by danielehrhardt** [comment]
Something new here?  Is it possible to pack app in to a single .exe file

**Comment by malept** [comment]
No.

**Comment by develar** [comment]
@danielehrhardt You can use `portable` target in the [electron-builder](https://www.electron.build/configuration/win).

**Comment by abicorios** [comment]
Also, it is possible by `electron-forge make`
See  https://github.com/electron-userland/electron-forge
By default in Windows the single exe is created by squirrel. After running it is extracted in C:\Users\user\AppData\Local\your_new_app, and rewrite it in each run. But user see alone executable, and almost all software work in a similar way.

**Comment by JulsSmile** [comment]
Also looking for the answer to this question.
Alternatively, you can pack an Electron application into an executable using a packer. For example this guide: [How to pack an Electron Application into a single executable file](https://www.boxedapp.com/boxedapppacker/usecases/pack_electron_app_into_single_exe.html)

**Comment by gregnr** [comment]
For those using [electron-forge](https://www.electronforge.io/config/makers), we've built a Maker plugin that builds a portable Windows `.exe` file using [electron-builder](https://www.electron.build/configuration/win)'s `portable` target under the hood:

https://github.com/rabbit-hole-syndrome/electron-forge-maker-portable

**Comment by edxu96** [comment]
> For those using [electron-forge](https://www.electronforge.io/config/makers), we've built a Maker plugin that builds a portable Windows `.exe` file using [electron-builder](https://www.electron.build/configuration/win)'s `portable` target under the hood:
> 
> https://github.com/rabbit-hole-syndrome/electron-forge-maker-portable

That's interesting. A quick question, is a portable app able to update itself?

Based on https://www.electronjs.org/docs/latest/api/auto-updater#windows, the app can only update itself, when it's installed:

![](https://user-images.githubusercontent.com/19307850/176473050-5a691929-1fa7-45ef-b52b-c535c5c52b48.png)
