### ISSUE TITLE
Windows Application Package Untrusted

### ISSUE THREAD

**Issue by ryanpager** [maxogden/electron-packager#245]
So I used the electron packager to create a windows bundle, and what not -- everything works great. But when people launch the application windows 7+ complains that the application is untrusted.

Is there some sort of certificate I need, or some sort of signing process I need to follow? I can't seem to figure this out, and having people complain that it is unsafe is a little annoying.

**Comment by malept** [comment]
electron-packager does not currently have signing support for Windows packages (see #32). However, we are more than happy to review and merge a pull request to add this feature.

**Comment by MarshallOfSound** [comment]
@malept In regards to a PR adding this feature, how do you feel about including the "signtool" binary like `electron-installer-windows` have?

**Comment by malept** [comment]
@MarshallOfSound 

Could you please explain what you mean by "include"?  In any event, the better choice for this would be to write a Windows signing node module and then create a pull request for electron-packager to integrate with it (similar to how OSX signing is being developed in #223).
