### ISSUE TITLE
electron-packager hangs

### ISSUE THREAD

**Issue by tevert** [maxogden/electron-packager#246]
* npm view electron-packager version: 5.2.1
* Command line args: "app MediaComplete --platform=win32 --arch=ia32" (where app is the subfolder my app's source is in, and MediaComplete is the desired output name)
* Building on Windows, for Windows
* No error message
* Unsure about reproduction - this happens every time for me, but clearly it's not happening for other people otherwise this issue would've already been logged.

Running electron-packager via NPM script or straight from command line hangs. I've tried running with the DEBUG variable set to "electron-download,extract-zip" as called out in another issue, but got no output. 

Manually injecting console.log statements showed that it called electron-packager/index.js, but the error callback passed to getNameAndVersion was never called. This doesn't seem right, since that error callback appears to be where the actual building is done (which could be a design smell itself). 

The strangest part is that, while it drops straight through, it doesn't terminate. Manual log statements show execution reaching the end of cli.js just fine, but then node decides it will keep running, and it gobbles up a whole CPU core while doing it. This implies to me that it's tight-looping, waiting for something, but I can't tell what. 

Let me know if there's any additional testing or info you need.

**Comment by malept** [comment]
Have you tried an older version? (I want to see if this is a regression.)

**Comment by tevert** [comment]
Went back to 5.0.0 - now it complains about a missing required argument. Adding the --version argument kicks it off. 

Going back to 5.2.1 - with the version argument, it works! So I guess the only regression is how arguments are handled. 

I'm getting a crash when I try to run it (cannot read property "name" of null), but that's presumably an issue in my code/config. This issue is resolved; thanks!
