### ISSUE TITLE
Use code coverage service?

### ISSUE THREAD

**Issue by malept** [maxogden/electron-packager#256]
I was curious and decided to see how well covered the package is with testcases. I used [nyc](https://github.com/bcoe/nyc) to do it - it's actually pretty good, ~96% (ignoring `cli.js`).

```
------------|----------|----------|----------|----------|----------------|
File        |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
------------|----------|----------|----------|----------|----------------|
 __root__/  |    91.37 |    78.47 |    98.72 |    96.13 |                |
  common.js |    93.75 |    73.53 |      100 |    98.65 |             57 |
  index.js  |    90.16 |    80.65 |      100 |    94.34 |... 171,189,190 |
  linux.js  |    81.82 |       50 |      100 |      100 |                |
  mac.js    |    92.65 |    83.33 |    93.33 |    95.38 |       64,65,86 |
  win32.js  |    90.63 |       80 |      100 |    96.67 |             41 |
------------|----------|----------|----------|----------|----------------|
All files   |    91.37 |    78.47 |    98.72 |    96.13 |                |
------------|----------|----------|----------|----------|----------------|
```

Do we want to use a code coverage service to monitor this (particularly for incoming pull requests), and if so, which one? I'm familiar with coveralls and codeclimate.

**Comment by maxogden** [comment]
my 2 cents is we should focus efforts on making the module smaller, since
that simplifies everything. but if the coverage stuff is easy to maintain
(e.g. no complex config files etc) then I'm +1

On Saturday, February 6, 2016, Mark Lee <notifications@github.com> wrote:

> I was curious and decided to see how well covered the package is with
> testcases. I used nyc <https://github.com/bcoe/nyc> to do it - it's
> actually pretty good, ~96% (ignoring cli.js).
>
> ------------|----------|----------|----------|----------|----------------|
> File        |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
> ------------|----------|----------|----------|----------|----------------|
>  __root__/  |    91.37 |    78.47 |    98.72 |    96.13 |                |
>   common.js |    93.75 |    73.53 |      100 |    98.65 |             57 |
>   index.js  |    90.16 |    80.65 |      100 |    94.34 |... 171,189,190 |
>   linux.js  |    81.82 |       50 |      100 |      100 |                |
>   mac.js    |    92.65 |    83.33 |    93.33 |    95.38 |       64,65,86 |
>   win32.js  |    90.63 |       80 |      100 |    96.67 |             41 |
> ------------|----------|----------|----------|----------|----------------|
> All files   |    91.37 |    78.47 |    98.72 |    96.13 |                |
> ------------|----------|----------|----------|----------|----------------|
>
> Do we want to use a code coverage service to monitor this (particularly
> for incoming pull requests), and if so, which one? I'm familiar with
> coveralls and codeclimate.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/maxogden/electron-packager/issues/256>.
>


-- 
Sent from my phone

**Comment by malept** [comment]
> my 2 cents is we should focus efforts on making the module smaller, since that simplifies everything.

Makes sense. I'll make sure to add that to CONTRIBUTING.md (#231).

> but if the coverage stuff is easy to maintain (e.g. no complex config files etc) then I'm +1

No complex config files. It's a pretty simple set of changes, I'll file a PR shortly.
