### ISSUE TITLE
Bundle ID for Helper EH and Helper NP

### ISSUE THREAD

**Issue by jasonhinkle** [maxogden/electron-packager#261]
The helper-bundle-id argument correctly sets the bundle id for the Helper app in it's plist file.  However the Helper EH and Helper NP still have the original electron bundle ID.

**Comment by jasonhinkle** [comment]
Going in a little deeper, the Bundle Name and Executable properties need to be updated as well in order to be accepted to the Mac App Store.  Here's an example of the NP plist that works and was accepted to the app store.

<img width="752" alt="screen shot 2016-02-09 at 9 13 05 pm" src="https://cloud.githubusercontent.com/assets/313176/12937099/1fbe2988-cf73-11e5-983e-3d3b604cff73.png">

**Comment by malept** [comment]
Would #253 solve this problem?

**Comment by jasonhinkle** [comment]
The extra info would probably work but really the packager already has the information it needs and is already renaming the helper files. So it seems like the default would be to put those values into the plist files. As is, the plist files are technically invalid, though it only comes into play when you try to submit to the app store.

**Comment by malept** [comment]
Evidently the author of #223 noticed this bug and is going to fix it.

**Comment by malept** [comment]
Fixed in #223.
