### ISSUE TITLE
Error: Unable to find a valid app

### ISSUE THREAD

**Issue by dkfiresky** [maxogden/electron-packager#264]
> Which version of electron-packager are you using?

5.2.1

> What cli arguments are you passing?

electron-packager ./src . --platform=win32 --arch=x64 --asar --version=0.36.7 --overwrite

> What platform are you running electron-packager on? What platform(s) are you building for?

Running on Windows 7, building for Windows 7

> Is there a stack trace in the error message you're seeing?

Error: Unable to find a valid app

> When possible, please provide instructions to reproduce your problem

Simply run the command above.

**Comment by dkfiresky** [comment]
The reason is that package.json is required in the sources directory.

**Comment by AndyRoyal** [comment]
这个问题按照上面的方式都不行

**Comment by AndyRoyal** [comment]
有没有解决了的
