### ISSUE TITLE
Error: Unable to find a valid app

### ISSUE THREAD

**Issue by olalonde** [maxogden/electron-packager#269]
Getting this error when opening my packaged OS X app:

```
Uncaught Exception:
Error: Unable to find a valid app
```

> Which version of electron-packager are you using?

5.2.1

> What CLI arguments are you passing? Alternatively, if you are using the API, what parameters are
> you passing to the `packager()` function?

```
electron-packager ./electron \"Some App\" --platform=darwin --arch=x64 --version=0.36.8 --icon=./electron/icons.icns
```

> What is the host platform are you running electron-packager on?

OS X 10.11

> What target platform(s)/architecture(s) are you building for?

OS X, x64

> Is there a stack trace in the error message you're seeing?

```
Uncaught Exception:
Error: Unable to find a valid app
    at Object.<anonymous> (/Users/.../Some App-darwin-x64/Some App.app/Contents/Resources/atom.asar/browser/lib/init.js:111:9)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Function.Module.runMain (module.js:457:10)
    at startup (node.js:151:18)
    at node.js:1007:3
```

> Please provide either a failing testcase or detailed steps to reproduce your problem.

**Comment by olalonde** [comment]
Oh think that's a duplicate of https://github.com/maxogden/electron-packager/issues/264. I don't have a package.json in my ./electron dir.

**Comment by challenger532** [comment]
just add the option ```--asar```
