### ISSUE TITLE
Windows rename error

### ISSUE THREAD

**Issue by jrudio** [maxogden/electron-packager#29]
Hi, I am getting the following error on windows 8.1. The target platform is obviously win32.
EXDEV, rename 'C:\Users\Justin\AppData\Local\Temp\electron-tmp-download\electron
-v0.25.3-win32-ia32.zip'

**Comment by maxogden** [comment]
@jrudio i'm not a windows expert, but a quick google suggests it might be because you are trying to write to a different device than your C:\ drive (http://stackoverflow.com/questions/21071303/node-js-exdev-rename-error), is that possible?

Otherwise maybe @jden has some ideas

**Comment by jden** [comment]
Hi, thanks for this, @jrudio ! Can you provide more information?

which version of electron-packager are you using?
what cli arguments are you passing?
Is there a stack trace in the error message you're seeing?

@maxogden indeed, that's my suspicion - which is what [mv](https://www.npmjs.com/package/mv) is supposed to be helping with

**Comment by maxogden** [comment]
@jrudio I just published a new version of `electron-download` (a dependency of `electron-packager`) that uses the `mv` module that @jden mentioned. Can you give that version a try? Just delete your `electron-packager` installation and re-install it from npm and you should get `electron-download@1.0.4`

**Comment by jrudio** [comment]
Yeah, I was trying to package up an app that was on my second hdd. I just tried it on my primary hdd and it's working fine. Although, I tried this after I had re-downloaded the electron-packager so I wasn't able to test it on the other version.

**Comment by maxogden** [comment]
@jrudio cool I think thats enough info to know we fixed it. thanks for testing

**Comment by jrudio** [comment]
No problem, and thanks for the quick answers! Even though I should have just googled it, lol.
