### ISSUE TITLE
windows support

### ISSUE THREAD

**Issue by maxogden** [maxogden/electron-packager#3]
shouldn't be too hard, I just haven't needed this yet

happy to accept a PR for it

**Comment by maxogden** [comment]
this will have to get resolved for windows support https://github.com/maxogden/atom-shell-packager/blob/d254289a156c00c4d40a9898cafdee9cebf5d17b/index.js#L94

**Comment by dboshardy** [comment]
I'm very curious about getting involved and to help with this.  What in general needs porting? And does my not knowing what needs to be done preclude my ability of helping with this?

**Comment by maxogden** [comment]
@dboshardy The goal of atom-shell-packager is to be a simple standalone CLI tool for building app executables. If you check out the code in the repo now you'll see that the process of building the mac app is pretty straightforward -- it just uses the provided mac app from Atom Shell and renames things/copies your files into it.

I haven't looked into creating a windows .exe, or a linux distributable app. I heard that there might be some code for creating windows .exes somewhere deep inside https://github.com/atom/atom-shell-starter. 

I'd start by figuring out how to package atom-shell apps as a windows .exe, and then see how hard it would be to implement. If you figure that out, then we can figure out a good way to merge it into this repo w/o making the existing code too complex

**Comment by jden** [comment]
I'mma take a stab at this sometime in the next few days. If someone else comes along and wants to work on it too, awesome! But here's an announcement of general intention.

**Comment by veloxy** [comment]
Could look at this for reference, looks like it has some solid support for major operating systems https://github.com/szwacz/electron-boilerplate

**Comment by ingro** [comment]
Another reference could be https://github.com/atom/grunt-electron-installer which use Squirrel

**Comment by maxogden** [comment]
basic windows support just landed in 3.4.0: https://github.com/maxogden/electron-packager/pull/20

the electron-boilerplate has an implementation of generating an installer. would be nice if it was in a standalone CLI tool like this. maybe we can port their implementation to this repo and add ourselves as a dependency in their boilerplate
