### ISSUE TITLE
Set product name, file description copyright on Windows

### ISSUE THREAD

**Issue by Ivshti** [maxogden/electron-packager#30]
Currently the .exe is branded as "Electron" and that shows up when right-clicking the app in the task bar, the task manager and several other key places.

This should be implemented in electron-packager as soon as the issue is resolved in rcedit and node-rcedit, because they currently cannot change those resources (CompanyName, FileDescription, LegalCopyright, ProductName).

I'll keep you posted on this.

**Comment by jden** [comment]
Cross-referencing those issues:

- https://github.com/atom/rcedit/issues/2
- https://github.com/mllrsohn/node-webkit-builder/issues/44

**Comment by jden** [comment]
I found this wrapper to resourcehacker, which is probably the most robust solution for modifying compilied Windows executables https://github.com/felicienfrancois/node-resourcehacker

We may be able to swap out rcedit for this instead.

**Comment by Rameshv** [comment]
@jden +1 for https://github.com/felicienfrancois/node-resourcehacker sounds like a good alternative.. i cant get rcedit work on my win 7/8 and server 2012. its annoying..   is anybody working on that..??

**Comment by jden** [comment]
@Rameshv after looking at that repo again, it doesn't appear to be a properly licensed redistribution of resourcehacker... indeed, it's not published on npm. We might be able to make a version of that which downloaded the resourcehacker exe via an npm postinstall script from the original distribution point

**Comment by Rameshv** [comment]
@jden yep thats my concern too. I made a quick fix by implementing the npm postinstall hook asyou suggested. You can see the PR here https://github.com/felicienfrancois/node-resourcehacker/pull/3. Waiting for the response from the author on this. 

Let me know if this works.

**Comment by felicienfrancois** [comment]
rcedit works pretty well and can do that (I use grunt-rcedit on my electron app).
This is not well documented but all thoose strings are "version-strings".
```
$ rcedit "path-to-exe" --set-version-string "CompanyName" "MyCompany"
$ rcedit "path-to-exe" --set-version-string "FileDescription" "This is an exe"
$ rcedit "path-to-exe" --set-version-string "LegalCopyright" "Copyright whatever"
$ rcedit "path-to-exe" --set-version-string "ProductName" "MyAwesomeProduct"
```

To get all the possible keys, you can open the exe with a gui program like resourcehacker or winresourcer

**Comment by Rameshv** [comment]
ah cool, thanks @felicienfrancois . yep rcedit works just fine with the version string info.. thanks for the hint.. it saved my day

**Comment by Rameshv** [comment]
hi @Ivshti , with this https://github.com/maxogden/electron-packager/pull/63 merge, you can do this now.. check the readme for more info

**Comment by alexwarren** [comment]
We can now change the version info in resources successfully, but this does *not* affect the name that appears when you right-click the app in the task bar. It still shows up as "Electron" there even if you change all the resource names.

**Comment by s-a** [comment]
This is true. Any ideas regarding @alexwarren 's problem? Maybe this one should be a new issue?

**Comment by felicienfrancois** [comment]
@alexwarren @s-a 
Windows title is handled by electron runtime.

It means that you have to set the title in your code when creating a BrowserWindow
https://github.com/atom/electron/blob/master/docs/api/browser-window.md#new-browserwindowoptions

Same for the icon, you have to set the runtime icon (ie window titlebar and tray icon) when creating a BrowserWindow

**Comment by s-a** [comment]
@felicienfrancois this is not what we mean. BrowserWindow setup is the same as when I set ```document.title```. We talk about the Windows task bar menu item caption. 

![image](https://cloud.githubusercontent.com/assets/1270662/8482065/61aaa988-20e7-11e5-892f-65a3de5b0a32.png)

**Comment by felicienfrancois** [comment]
@s-a ok sorry.

It seems the name in the taskbar depends if it have been pined and how:
- If not pined, depends on runtime. Seems to be not consistant across electron versions. Maybe the undocumented "productName" entry of package.json could do the trick.
- If pined by dragging a shortcut, it keep the name of the shortcut
- If pined by dragging the exe, it keep the name of the exe
- If pined by right click > Pin when the program was running, it keep the name at this time.

It may also depends on the OS. Windows 10 has changed things. there is an open issue regarding pining on windows 10 https://github.com/atom/electron/issues/1954

**Comment by malept** [comment]
Closing since #63 was merged.
