### ISSUE TITLE
`--out` inconsistency

### ISSUE THREAD

**Issue by sindresorhus** [maxogden/electron-packager#38]
If I specify `--out=dist` it will put the contents in:

- OS X: `dist/Foo.app/`
- Windows: `dist/Foo-win32/`
- Linux: `dist/`

Notice how on Linux the contents is put directly into the `--out` folder. This looks like a bug.

**Comment by malept** [comment]
Either Linux is the odd one out or Windows is. OS X is a special exception because of how Mac apps work. I'd argue that Windows is being weird - why does it need to be in a subfolder of the `args.out` folder?

**Comment by sindresorhus** [comment]
I think it's Linux, because if I don't specify a `--out` the content ends up in `./App-linux/`.

**Comment by malept** [comment]
It makes sense to default to `./App-linux`, so that it doesn't pollute the current directory. If `args.out` is always appended by `/$APP_NAME-linux`, that will make #33 more complex (i.e., having to rename that folder before packaging it up).

**Comment by jden** [comment]
In conjunction with #40, I think the output folder should default to a combination of `./$APP_NAME-$PLATFORM-$ARCH`

**Comment by jenslind** [comment]
I would prefer: `./out-folder/$PLATFORM/$ARCH/foo.app` or `./out-folder/$PLATFORM-$ARCH/foo.app` especially when running with `--all`

**Comment by englercj** [comment]
+1 Just hit this today, I like using platform/arch in the output folder. I agree with @jenslind I think `./out-folder/$PLATFORM/$ARCH/...` is best, and `./out-folder/$PLATFORM-$ARCH/...` is good.

**Comment by kfranqueiro** [comment]
Regarding which one is the odd one out, I'd also say it's Linux, for a couple of reasons:

* It doesn't use `os.tmpdir()` to do its work first like Win/Mac
* Whereas the Win/Mac scripts effectively do `path.join(opts.out || process.cwd(), ...)`, the Linux script does `opts.out || path.join(process.cwd(), ...)`

**Comment by maxogden** [comment]
I fixed the Linux inconsistency today in https://github.com/maxogden/electron-packager/commit/86edff69d80d2d761877c476fa621ad67bba1935, but leaving this open as there are some other good suggestions we can think about in the future
