### ISSUE TITLE
default ignores and --ignore not working (windows)

### ISSUE THREAD

**Issue by zaggino** [maxogden/electron-packager#44]
Hi, I'm using latest packager `4.1.0` and building the electron app using (in msysgit bash shell):
```
npm run bundle-win
```
in package.json I've defined
```
"bundle-win": "bundle.sh win32 x64 0.26.0",
```
which executes following script:
```
#!/bin/sh
electron-packager . Bracketron --platform=$1 --arch=$2 --version=$3 --ignore=node_modules/electron-rebuild
```
but the problem is, that neither `electron-rebuild` or default excludes (https://github.com/maxogden/electron-packager/commit/892b15fc306ee67bd1ea8a6aa6a1c799443b37f2) are being excluded from the build folder (otherwise it builds fine)

repo is here https://github.com/zaggino/brackets-electron

**Comment by jenslind** [comment]
Hmm, I can't reproduce this issue on Mac. Does your linux and mac builds work as expected?

**Comment by zaggino** [comment]
Can you please try the repo above? https://github.com/zaggino/brackets-electron
`npm run bundle-mac` doesn't even copy the app files into the `Contents/Resources/app` folder for some reason (it does copy on Windows but ignores excludes)

**Comment by zaggino** [comment]
Nevermind, found one issue, going to submit a PR

**Comment by zaggino** [comment]
PR for Mac is up, I'll check what's wrong on Windows too

**Comment by zaggino** [comment]
PR for Windows is up too.

**Comment by zaggino** [comment]
@maxogden another issue with `4.1.1`:
I have this in my shell script:
```
electron-packager . Bracketron --platform=$1 --arch=$2 --version=$3 --ignore='/node_modules/electron-rebuild($|/)'
```
but minimist will convert this to:
```
C:/Program Files (x86)/Git/node_modules/electron-rebuild($|/)
```
I've put console.log here: https://github.com/maxogden/electron-packager/blob/master/cli.js#L4

**Comment by zaggino** [comment]
Actually this is done even before it reaches minimist for some reason, sorry. I need to check why.

**Comment by zaggino** [comment]
Ok, I actually need to do
```
--ignore='./node_modules/electron-rebuild$'
```
to make it work without resolving the first `/` to `C:/Program Files (x86)/Git/`

But it excludes correctly now. You can close this or make some notes based on my findings into the README if you wish. Thanks for merging the PRs.

**Comment by zaggino** [comment]
Ah, I'm spamming here but still not good. I need to exlude a folder `tools` from my app but I don't want to exclude a folder `something/tools` too. Excludes should only be matched against the root of the app.
