### ISSUE TITLE
default_app and atom.asar remain in Contents/Resources

### ISSUE THREAD

**Issue by orderedlist** [maxogden/electron-packager#49]
Would be nice to be able to remove all the default Electron files when building. I'm sure this exists on Windows too, but I haven't looked into what files remain.

**Comment by jden** [comment]
Oops, you're right - those certainly shouldn't be there. Thanks for filing this issue, @orderedlist! Just to confirm, what version of electron-packager are you using, what OS are you running it on, and what OS are you building for?

Thanks!

**Comment by maxogden** [comment]
+1, they are included in the default electron zip that gets downloaded from the electron releases and we never remove them

**Comment by orderedlist** [comment]
Hmm, some experimentation seems to show that, at least as of right now, removing those files causes Electron to do weird things. `atom.asar` seems to be required, and removing `default_app` means you can't run the Electron command line and pass in a path argument to use that folder. This seems pretty buggy, so I might dig into Electron and see if it's any requirements there we can fix.

**Comment by kfranqueiro** [comment]
FWIW, I noticed that the `linux` module seems to actually move the user's app files *into* `default_app`.  The other two modules don't do this.  Wonder if that's a safe thing to do and if we could do it everywhere...

**Comment by malept** [comment]
> FWIW, I noticed that the `linux` module seems to actually move the user's app files into `default_app`.

That was the only way I could figure out how to get my app to run correctly on Linux.

**Comment by kfranqueiro** [comment]
> That was the only way I could figure out how to get my app to run correctly on Linux.

Huh, that's peculiar.  It's working for me on Linux from `app` or `app.asar` on my refactored branch.

**Comment by unindented** [comment]
@kfranqueiro Now that your branch has been merged, do you think it would be safe to remove `default_app`?

**Comment by romaincointepas** [comment]
Hey, any update on this?

The famous electron-boilerplate seems to be removing those:
https://github.com/szwacz/electron-boilerplate/blob/master/tasks/release_osx.js#L29-L33

**Comment by Mingling94** [comment]
Correct me if I'm wrong, but atom.asar is required, but default_app should be removed since no one should be trying to use electron via command line when you're sending out a release of your app. electron-packager should remove the default_app folder by default

**Comment by malept** [comment]
If someone wants to submit a PR for this change, they should feel free to do so - assuming it's been tested on all platforms.

**Comment by seanzer** [comment]
I agree that no one should be trying to use the packaged electron on the command line. Especially once it's been renamed, which electron-packager allows for, so I don't think many people would miss default_app. Though, I don't understand why it's required on Linux.

**Comment by havenchyk** [comment]
Hey, it there any updates here?

**Comment by malept** [comment]
I haven't found time to test #206.
