### ISSUE TITLE
Not all details are changed

### ISSUE THREAD

**Issue by iamdriz** [maxogden/electron-packager#52]
When using this packager, the File description, Product name, and Copyright are still Election and GitHub even though I used `Cameron` for the app name, it changed the exe to Cameron.exe but the other details are unchanged.

![image](https://cloud.githubusercontent.com/assets/801252/7912339/77523b8a-085e-11e5-89f3-20247ba35f85.png)

Can these be added to the packager as options?

**Comment by malept** [comment]
Thanks for filing a bug. There's actually already one open about this (#30), so you should subscribe to that one to get updates about its implementation.
