### ISSUE TITLE
ignore filter matching to path in cwd 

### ISSUE THREAD

**Issue by chentsulin** [maxogden/electron-packager#54]
nsp's filter test regexp matching to a whole path name

```
/Users/chentsulin/Projects/test/electron-react-boilerplate
```
will match `'/test($|/)'` in `ignore` option:

```js
ignore: [
    '/test($|/)'
]
```

It will ignore copy of whole app and cause some unexpected behaviors.

**Comment by jden** [comment]
The strategy in #55 of not matching `--ignore` patterns against the cwd works, but it seems like it should ignore the `<sourcedir>` instead, which may or may not be the cwd

**Comment by chentsulin** [comment]
Is it appropriate if I use `require('path').resolve(opts.dir)` instead of `process.cwd()`?

**Comment by kfranqueiro** [comment]
This was never closed even though #55 was merged.  However, it has resurfaced (see #84).  I will be including a fix to reinstate this fix in the branch I am planning to PR shortly.

**Comment by kfranqueiro** [comment]
Now that #88 is merged, this should again be resolved.  Any objections to closing this?

**Comment by malept** [comment]
No objections, so closing.
