### ISSUE TITLE
Error: Uncaught Exception: Error: Unable to find a valid app     at Object.<anonymous> ...

### ISSUE THREAD

**Issue by ahadcove** [maxogden/electron-packager#550]
I have been trying to package up my app with no luck. At first I was trying to use electron-packager to package up my whole project without ng build, but this gave me a static index.html, breaking my angular 2 app. Now I am using electron-packager on my dist folder after using ng build and I am getting this error:
``` 
Uncaught Exception:
Error: Unable to find a valid app
    at Object.<anonymous> .../App.app/Contents/Resources/electron.asar/browser/init.js:121:9)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:402:7)
    at startup (bootstrap_node.js:157:9)
    at bootstrap_node.js:521:3
```

I am passing:  

  ```
 "macBuild":"electron-packager ./dist App --out=releases/ --platform=darwin --arch=all --ignore=electron-packager --icon=icon.icns --overwrite --asar",
```

This also deletes my node_modules for some reason after it builds.

Originally I was passing:
```
    "macBuild":"electron-packager . App --out=releases/ --platform=darwin --arch=all --ignore=electron-packager --icon=icon.icns --overwrite --asar",
```
But that gave me a static index

**Comment by MarshallOfSound** [comment]
If you're having issues with using Angular 2 with Electron I'd recommend using [`electron-forge`](https://github.com/electron-userland/electron-forge). 

It has built in support for Angular 2 (thanks to `electron-compile`), you can see an example here

https://github.com/electron-userland/forge-examples/tree/master/angular2

It should handle all your troubles for you while still using `electron-packager` under the hood 👍

**Comment by AhadCove** [comment]
I just attempted electron-forge import, but it failed when trying to install electron-prebuilt-compile, not sure if I should continue messing with it or not

**Comment by malept** [comment]
Please file a bug in the Electron Forge project (I think it has to do with the version of Electron you're using). With regards to your Electron Packager problem, my suspicion is that you're not setting `main` in `package.json` to an appropriate value.

**Comment by MarshallOfSound** [comment]
>  but it failed when trying to install electron-prebuilt-compile, 

Interesting, what error does it fail with?

**Comment by AhadCove** [comment]
```
An unhandled error has occurred inside Forge:
Failed to install modules: ["electron-prebuilt-compile@1.4.13"]

With output: npm ERR! Darwin 16.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "electron-prebuilt-compile@1.4.13" "--save-exact" "--save"
npm ERR! node v7.4.0
npm ERR! npm  v4.0.5
npm ERR! code ETARGET
```

**Comment by malept** [comment]
Yup, I've notified the maintainer of electron-prebuilt-compile.

**Comment by AhadCove** [comment]
Okay so should I continue to use this module or...??

**Comment by malept** [comment]
Use 1.4.12 temporarily.
