### ISSUE TITLE
Error building from non-OS volume

### ISSUE THREAD

**Issue by johnmuhl** [maxogden/electron-packager#60]
If my Electron application is on a different volume than my OS `electron-packager ./ MyApp …` fails with `EXDEV: cross-device link not permitted` when it gets to https://github.com/maxogden/electron-packager/blob/master/mac.js#L106 and tries to move (instead of copy) the packaged application to the output directory.

**Comment by maxogden** [comment]
@johnmuhl can you provide this info so we can help triage? https://github.com/maxogden/electron-packager/blob/master/CONTRIBUTING.md

**Comment by johnmuhl** [comment]
> - Which version of electron-packager are you using?

4.1.2

> - What cli arguments are you passing?

`electron-packager ./ MyApp --platform=darwin --arch=x64 --version=0.27.3`

> - What platform are you running electron-packager on? What platform(s) are you building for?

Mac OS X 10.9.5

> - Is there a stack trace in the error message you're seeing?

The complete output of the command above is:
~~~
Packaging app for platform darwin x64 using electron v0.27.3
EXDEV: cross-device link not permitted, rename '/var/folders/vv/54sdz8qj3b93zdkd8dchc5v00000gp/T/electron-packager-mac/MyApp.app' -> '/Volumes/home/jm/Source/johnmuhl/MyApp/MyApp.app'
~~~

**Comment by maxogden** [comment]
excellent thanks, will try and reproduce. we've seen similar issues on
Windows so I wasn't sure if it was a Windows issue

**Comment by malept** [comment]
I believe this (roughly) will solve it: https://github.com/atom/scandal/pull/13/files

I can file a pull request to adapt that code, but there's a pull request before this that I'd like to make first (namely, reducing duplicated code).
