### ISSUE TITLE
electron-packager doesn't rename Electron Helper.app

### ISSUE THREAD

**Issue by kfranqueiro** [maxogden/electron-packager#65]
If you look in Activity Monitor while running an application packaged with electron-packager, you'll see your application under the desired name, but you'll also still see an Electron Helper process.

As far as I can tell, renaming the Electron Helper directories under Frameworks *and* the binaries under their Contents/MacOS subdirectories resolves this.

**Comment by jden** [comment]
This seems related to my question in https://github.com/maxogden/electron-packager/pull/63#issuecomment-112503269

@kfranqueiro if you'd like, we'd be willing to accept a pull request for this.

**Comment by kfranqueiro** [comment]
I've submitted PR #76.

You probably don't want to hear this because chances are your minds are already made up, but I am compelled to mention that this probably could have taken half the time it took me if this code were more well-structured (dare I say even using a promises library - though I imagine at least [async](https://github.com/caolan/async) could still offer an improvement).  It took me a while just to figure out where it was safe to add this without breaking something and without making it even harder to maintain (originally looking inside the `moveApp` function).

**Comment by maxogden** [comment]
@kfranqueiro thanks for the feedback. we definitely need tests to catch regressions. this is currently the low priority side project of a handful of folks so nobody has taken the time to do a proper test suite yet. I'll open an issue for that! Also I could see us using https://www.npmjs.com/package/run-series in a few spots to improve readability and encapsulation as well.

**Comment by jden** [comment]
@kfranqueiro your point is well made - having cleaner code makes it easier for others to understand & contribute to a project, which I think is a goal all of the current contributors share. As @maxogden said, this is a small module that grew to include cross-platform support and additional features which resulted in more complicated code structure. If you're interested in helping, that would be awesome!

**Comment by kfranqueiro** [comment]
Thanks for the replies.  I might be interested, but I suspect that we might want to get a few PRs merged beforehand to avoid needing ugly rebases.  Meanwhile I was inclined to maybe think about starting a stab at #77 this weekend or something to start with, which would likely give me a leg in to bring in run-series anyway.
