### ISSUE TITLE
Issue with outputting Win32 versu Win64 apps

### ISSUE THREAD

**Issue by Stephn-R** [maxogden/electron-packager#70]
```shell
electron-packager . ${APP_NAME} --platform=win32 --arch=ia32 --version=${ELECTRON_VERSION} --out=${OUTPUT_DIR}
```

```shell
electron-packager . ${APP_NAME} --platform=win32 --arch=x64 --version=${ELECTRON_VERSION} --out=${OUTPUT_DIR}
```

Both of these calls export the same root folder ```${APP_NAME}-win32```

Shouldn't it be expected that the Win64 version would have 64 as a suffix?

**Comment by jden** [comment]
we're using the node nomenclature for platform and architecture, so 64 bit windows would be win32-x64. I think it would be a good idea to include architecture in output directory names.
Related discussion: https://github.com/maxogden/electron-packager/issues/38

**Comment by Stephn-R** [comment]
Thank you @jden
