### ISSUE TITLE
Dependency on mv

### ISSUE THREAD

**Issue by kfranqueiro** [maxogden/electron-packager#78]
Out of curiosity, is there a convincing reason for this package's dependency on `mv`?  As far as I can tell, it only seems to use it once - for a rename of the exe file on Windows, which I'd think could just as easily use `fs.rename`.

Sorry this is such a nit-pick.  If you see fit to remove it I can submit a PR.

**Comment by malept** [comment]
Does `mv` work between folders? `fs.rename` does not (see #60).

**Comment by kfranqueiro** [comment]
AFAICT, the one use of `mv` is simply renaming within the same folder: https://github.com/maxogden/electron-packager/blob/v4.1.3/win32.js#L25

I was under the impression #60 was more specifically related to trying to move a folder with symlinks across drives.  I'm not sure whether `mv` can accommodate that, but the PR for it doesn't rely on `mv` either way.

**Comment by malept** [comment]
I was wondering whether I can replace the PR in #74 with just using `mv`.

**Comment by jden** [comment]
`mv` is used to prevent EXDEV errors when moving a file across physical drives on some platforms, especially win32. `fs.rename` should not be used.

**Comment by malept** [comment]
OK, I'll update my PR later today to use `mv`. I'm closing this issue since we're going to keep using `mv`.

**Comment by kfranqueiro** [comment]
I get the whole cross-device thing, which is what #74 is about, so using `mv` makes sense there, yeah.  The only place that is *currently* using `mv` is a rename of a single file within the same directory it's already in, and other occurrences of that (e.g. in `linux.js`) use `rename`, which is why I originally flagged this.

Not sure if we want to do something to make other `rename` uses more consistent ultimately, but I agree to `mv` staying if it can be used for #74.
