### ISSUE TITLE
Question about is_win32 flag

### ISSUE THREAD

**Issue by kfranqueiro** [maxogden/electron-packager#79]
I've been digging through the code while working on my `all` branch, and noticed [this block in common.js](https://github.com/maxogden/electron-packager/blob/v4.1.3/common.js#L32-L35).

I wouldn't necessarily bat an eye at this in itself, but what strikes me as odd is that it's only set to true specifically in the `win32` module.  I would think that if anything, this needs to be set to true when the *host platform* (i.e. `os.platform()`) is win32, not the target platform.

Can anyone corroborate this?

**Comment by malept** [comment]
>  I would think that if anything, this needs to be set to true when the host platform (i.e. `os.platform()`) is win32, not the target platform.

Perhaps. It was originally only added to `win32.js` (via #46), so when I refactored, I didn't want to change that behavior.

**Comment by kfranqueiro** [comment]
I've been manually testing everything I can think of and `ignore` is one of the last things on my list, so hopefully I'll hit that sometime in the coming week to confirm this.

**Comment by kfranqueiro** [comment]
I've confirmed tonight that this is indeed wrong - for example, `--ignore='ignore/this'` will ignore correctly for windows builds on windows, but not linux/mac builds on windows.  The check should be detecting against the host platform, not the platform being targeted.  (Or perhaps look at `path.sep` and if it's not already `/`, replace based on it.)

I should be able to come up with a PR for this.
