### ISSUE TITLE
How does '--asar=true' works?

### ISSUE THREAD

**Issue by Enkows** [maxogden/electron-packager#81]
When I set `asar` as `true`, the packaged app looks like this:

```
electron/Electron.app/Contents/Resources/
├─┬ app/
│ ├── package.json
│ ├── main.js
│ └── index.html
└─┬ resources/
  └── app.asar
```

The packager puts all source codes under `app`, and create an empty app.asar file under `resources`.

---
Platform: OS X 10.10.3
Node: 0.12.4
Version: 4.1.3
CLI Arguments:
- Platform: Darwin
- Arch: x64
- Version: 0.28.2
- Asar: true

**Comment by maxogden** [comment]
thanks for the bug report! heres the line of code we're calling in the implementation for reference https://github.com/maxogden/electron-packager/blob/554f3b735483319450c2ad8d0e0cba90e041ebe2/common.js#L10, it's pretty weird the `asar` file that you get is empty. 

I or another maintainer will try and reproduce when we get a chance

**Comment by kfranqueiro** [comment]
This sounds like a similar problem to what #73 is trying to solve.  Apparently it's an issue on more than a single platform.  It certainly looks as if `mac.js` is already adding `Resources` to the path, and then `asarApp` is adding `resources` again, which is wrong.

**Comment by masom** [comment]
@kfranqueiro yep. On windows the app is packaged at `/path/to/app/resources` but `electron-packager` adds another `resources` path component. This probably happened by porting the os x code to windows. The OS X app generates the resources folder under the `MyApp.app/Resources` which does not exists on windows.

**Comment by masom** [comment]
Seems like problems got introduced in https://github.com/maxogden/electron-packager/commit/81340093eea627e854f0a674e5356552e237d265

**Comment by masom** [comment]
https://github.com/maxogden/electron-packager/commit/81340093eea627e854f0a674e5356552e237d265#diff-a16e9b0497c5d6579f17c2c139cb3abaL140 was modified to append `resources` but some file operations did not take this into considerations.

**Comment by malept** [comment]
Yeah, sorry about that. Give me a second to revert the behavior.

**Comment by masom** [comment]
@malept #73 should fix it.

**Comment by malept** [comment]
@masom #73 is not quite right in the Mac code, it adds an extra folder.

@Enkows please test 178b3d4 with a Mac build, it reverted the behavior to what it was before my refactoring.

**Comment by masom** [comment]
@malept 178b3d4 works for us on both windows and OS X

**Comment by kfranqueiro** [comment]
The Mac code should be fine now, as it already adds `Resources` on its side of the code.

**Comment by Enkows** [comment]
@malept @masom 
https://github.com/maxogden/electron-packager/commit/178b3d4cd3332773338e33fc1e45681f80fdfb28 fixed the path issue, but the `app.asar` still has a problem.

```
$ cp electron/Electron.app/Contents/Resources/app.asar app.asar
$ asar list app.asar
/app.asar

$ asar extract app.asar app/app.asar
$ asar list app/app.asar
/package.json
/index.html
/main.js
```

It seems the .asar file packaged twice.
