### ISSUE TITLE
Better ignore options

### ISSUE THREAD

**Issue by Agrosis** [maxogden/electron-packager#86]
IMO, the ignore option is kind of messy after I have a lot of development modules, you guys think it would be better to just add in a --ignore-dev-modules flag? If you approve, I'll go ahead 'n make a pull request.

**Comment by kfranqueiro** [comment]
Are you essentially referring to ignoring devDependencies?  There is already a `--prune` option that effectively achieves the same result, though it ends up copying the files first and then running `npm prune --production`, so I suppose avoiding copying them in the first place would be better.

**Comment by maxogden** [comment]
closing this as there are lots of existing ignore related issues
