### ISSUE TITLE
Linux icon doesn't appear

### ISSUE THREAD

**Issue by alexwarren** [maxogden/electron-packager#90]
Are there any special requirements for Linux icons? My understanding is that a PNG file should work. But when I pass a PNG file into the `--icon` option, it doesn't appear in Ubuntu. The icon remains as a default "?".

I've tried various sizes - 1024x1024, 128x128, 96x96, but I see the same behaviour.

I'm using `--arch=x64` with Ubuntu 14.04, packaging Electron v0.27.3.

**Comment by malept** [comment]
Is this Unity?

**Comment by alexwarren** [comment]
@malept Not sure I understand the question, what does Unity have to do with electron-packager? It's not something I'm using.

**Comment by malept** [comment]
I don't understand where you're trying to see the icon. Perhaps you could give a screenshot?

**Comment by alexwarren** [comment]
Oh I see Unity is the name of a graphical shell. Well... I dunno, I'm just using whatever Ubuntu's default is.

**Comment by alexwarren** [comment]
This is the icon that appears in the app launcher on the left when the app is running:

![screen shot 2015-07-01 at 20 58 12](https://cloud.githubusercontent.com/assets/418188/8463634/ea02237e-2033-11e5-96bc-947c0e872523.png)

**Comment by malept** [comment]
Have you set the icon of the `BrowserWindow` in your Electron app, per http://electron.atom.io/docs/v0.28.0/api/browser-window/ ?

**Comment by alexwarren** [comment]
Ah, fantastic, didn't realise that needed to be set there (as it works without it on Windows and OS X). Thanks!

**Comment by grofit** [comment]
I do not get an icon in the filesystem even with an icon set, just to confirm should the format of the icon be an image format, i.e. `icon: "my-icon.png"` or an ico file `icon: "my-file.ico"` as I am using the latter and it works fine in windows, but linux shows nothing.

**Comment by malept** [comment]
I would imagine that using a `.ico` as the file format would not work with Unity.

**Comment by strongant** [comment]
var iconPath = __dirname + '/app/assets/img/appledisk.png';

function createWindow() {
  mainWindow = new BrowserWindow({
    width: 1000,
    height: 1000,
    icon: iconPath
  });

when electron start, i see nothing.[https://cloud.githubusercontent.com/assets/418188/8463634/ea02237e-2033-11e5-96bc-947c0e872523.png](url)

**Comment by malept** [comment]
@strongant check the application bundle and make sure the icon path you specify is relative to the JavaScript file you're calling it from.

**Comment by strongant** [comment]
electron-packager . DiskClone --platform linux --arch x64 --prune  --out=dist/ --overwrite  --icon =app/assets/img/appledisk.png --prune  --ignore=node_modules/electron-prebuilt --ignore=node_modules/electron-packager --ignore =.git

**Comment by strongant** [comment]
![test](https://cloud.githubusercontent.com/assets/7685936/15998770/8665979a-3173-11e6-8f53-bd95d6d513f8.png)

**Comment by strongant** [comment]
why?

**Comment by malept** [comment]
@strongant I mean in the `dist` directory that you specified in `--out`, and please respond in the other GitHub issue that you created.
