### ISSUE TITLE
Binary no longer in path?

### ISSUE THREAD

**Issue by krainboltgreene** [maxogden/electron-packager#91]
```
$ electron-packager
zsh: command not found: electron-packager
```

Every other binary in my project is working fine.

**Comment by malept** [comment]
Is this version 5?

**Comment by krainboltgreene** [comment]
Yes, we're tracking master.

**Comment by krainboltgreene** [comment]
Seems to work fine when inside a npm package.json `scripts` key.

**Comment by maxogden** [comment]
hmm very weird, the only 2 requirements are currently met: https://github.com/maxogden/electron-packager/blob/dcf1da5d1afb3a06afac0b3723c34bdba327ced4/package.json#L7 https://github.com/maxogden/electron-packager/blob/dcf1da5d1afb3a06afac0b3723c34bdba327ced4/cli.js#L1

**Comment by jestersimpps** [comment]
a global install stolved it for me: npm install electron-packager -g

**Comment by krainboltgreene** [comment]
I think it was just a fluke.
